// Nigeria Government & Private Housing Estates — structured data
// Compiled from public news/government sources. See data.md for the
// original Lagos working notes. FCT and Rivers entries were compiled the
// same way: public agency sites, news coverage, and real estate
// aggregators, not verified government records.
//
// Coordinates are neighbourhood-level approximations (geocoded from place
// names), not verified street addresses. Good enough to place a pin on a
// map for a demo; not good enough to route a courier.
//
// type: "Government" — initiated, land-granted, or financed by a
//   government body (federal, state, or a public-private partnership
//   where the public partner is the anchor). "Private" — a commercial
//   developer's own project, no government initiation.

const AGENCIES = {
  HOMS: {
    name: "Lagos State Mortgage Board (Lagos HOMS)",
    phone: "07044519311 / 08124817363",
    email: "info@lagoshoms.gov.ng",
    website: "https://www.lagoshoms.gov.ng"
  },
  LSDPC: {
    name: "Lagos State Development and Property Corporation (LSDPC)",
    phone: null,
    email: null,
    website: "https://lsdpc.gov.ng"
  },
  LAGOS_MINISTRY: {
    name: "Lagos State Ministry of Housing",
    phone: null,
    email: null,
    website: "https://housing.lagosstate.gov.ng"
  },
  FMHUD: {
    name: "Federal Ministry of Housing & Urban Development (FMHUD)",
    phone: null,
    email: null,
    website: "https://fmhud.gov.ng"
  },
  FHA: {
    name: "Federal Housing Authority (FHA)",
    phone: "+234 911 541 8960",
    email: "info@fha.gov.ng",
    website: "https://fha.gov.ng"
  },
  FCDA: {
    name: "Federal Capital Development Authority (FCDA)",
    phone: "+234 9 234 1525",
    email: null,
    website: "https://fcda.gov.ng"
  },
  RSHPDA: {
    name: "Rivers State Housing and Property Development Authority (RSHPDA)",
    phone: "+234 703 554 7870",
    email: "info@rshpda.gov.ng",
    website: "https://rshpda.gov.ng"
  },
  FMBN: {
    name: "Federal Mortgage Bank of Nigeria (FMBN)",
    phone: null,
    email: null,
    website: "https://www.fmbn.gov.ng"
  },
  RIVERS_GOVT: {
    name: "Rivers State Government",
    phone: null,
    email: null,
    website: "https://riversstate.gov.ng"
  },
  OGSHC: {
    name: "Ogun State Housing Corporation (OGSHC)",
    phone: "+234 817 202 7772",
    email: "info@ogshc.og.gov.ng",
    website: "https://ogshc.og.gov.ng"
  },
  OPIC: {
    name: "Ogun State Property & Investment Corporation (OPIC)",
    phone: "+234 811 289 2020",
    email: "info@opicgroup.com",
    website: "https://www.opicgroup.com"
  },
  KANO_GOVT: {
    name: "Kano State Government (Ministry of Housing Development)",
    phone: "+234 704 909 9994",
    email: "info@kanostate.gov.ng",
    website: "https://kanostate.gov.ng"
  },
  FHFL: {
    name: "Family Homes Funds Ltd (FHFL)",
    phone: null,
    email: null,
    website: "https://fhfl.com.ng"
  },
  ESHDC: {
    name: "Enugu State Housing Development Corporation (ESHDC)",
    phone: "08034886364",
    email: null,
    website: "https://eshdc.en.gov.ng"
  }
};

// Federal mortgage financing option shown as a general, non-endorsing
// link-out — not tied to any specific estate's developer network.
const MREIF = {
  name: "MREIF (Mortgage Refinance Initiative Fund)",
  rate: "9.75% p.a. fixed",
  term: "Up to 20 years",
  equity: "From 10% equity",
  signupUrl: "https://housing.mreif.com.ng/sign-up",
  prequalifyUrl: "https://housing.mreif.com.ng/pre-qualifier",
  infoUrl: "https://www.mreif.com.ng/",
  disclaimer: "Federal mortgage program managed by ARM for Ministry of Finance Incorporated. housedata.ng is not affiliated with MREIF and cannot confirm any specific estate is in MREIF's approved developer network — check eligibility directly."
};

const ESTATES = [
  // ---------------------------------------------------------------
  // LAGOS — Government
  // ---------------------------------------------------------------
  {
    id: "lagos-oba-adeboruwa",
    name: "Oba Adeboruwa Estate",
    state: "Lagos", type: "Government",
    lat: 6.6100, lng: 3.5150,
    area: "Igbogbo, Ikorodu",
    lga: "Ikorodu",
    unitTypes: "1, 2, 3 bed flats",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.HOMS.name,
    enquiryContact: AGENCIES.HOMS,
    sourceNote: "Completed, rent-to-own available. Source: NPC, EleniyanCares — publicly reported, verify before publishing."
  },
  {
    id: "lagos-millennium-i",
    name: "Millennium Housing Scheme",
    state: "Lagos", type: "Government",
    lat: 6.6180, lng: 3.2980,
    area: "Iloro, Agege",
    lga: "Agege",
    unitTypes: "3 bed flats",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.LAGOS_MINISTRY.name,
    enquiryContact: AGENCIES.LAGOS_MINISTRY,
    sourceNote: "Source: NPC — publicly reported, verify before publishing."
  },
  {
    id: "lagos-millennium-ii",
    name: "Millennium Housing Scheme II",
    state: "Lagos", type: "Government",
    lat: 6.6480, lng: 3.2870,
    area: "Ojokoro, Ijaiye",
    lga: "Ijaiye",
    unitTypes: "3 bed flats",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.LAGOS_MINISTRY.name,
    enquiryContact: AGENCIES.LAGOS_MINISTRY,
    sourceNote: "Source: NPC — publicly reported, verify before publishing."
  },
  {
    id: "lagos-jubilee",
    name: "Jubilee Housing Estate",
    state: "Lagos", type: "Government",
    lat: 6.5900, lng: 3.9700,
    area: "Odoragunshin, Epe",
    lga: "Epe",
    unitTypes: "Room & parlour, 1 & 2 bed bungalows",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.LAGOS_MINISTRY.name,
    enquiryContact: AGENCIES.LAGOS_MINISTRY,
    sourceNote: "Source: NPC — publicly reported, verify before publishing."
  },
  {
    id: "lagos-jakande-garden",
    name: "Jakande Garden Estate",
    state: "Lagos", type: "Government",
    lat: 6.5200, lng: 3.2270,
    area: "Igando",
    lga: "Alimosho",
    unitTypes: "Flats",
    status: "Completed",
    units: "492 units",
    priceRange: null,
    agency: AGENCIES.LSDPC.name,
    enquiryContact: AGENCIES.LSDPC,
    sourceNote: "Source: Ballers.ng — publicly reported, verify before publishing."
  },
  {
    id: "lagos-iponri",
    name: "Iponri Estate",
    state: "Lagos", type: "Government",
    lat: 6.4931, lng: 3.3627,
    area: "Iponri",
    lga: "Surulere",
    unitTypes: "Various",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.LSDPC.name,
    enquiryContact: AGENCIES.LSDPC,
    sourceNote: "Surulere / Lagos Island axis. Source: Ballers.ng — publicly reported, verify before publishing."
  },
  {
    id: "lagos-homs-ibeshe",
    name: "Lagos HOMS – Ibeshe",
    state: "Lagos", type: "Government",
    lat: 6.6330, lng: 3.5460,
    area: "Ibeshe, Ikorodu",
    lga: "Ikorodu",
    unitTypes: "Residential",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.HOMS.name,
    enquiryContact: AGENCIES.HOMS,
    sourceNote: "Source: Estate Intel — publicly reported, verify before publishing."
  },
  {
    id: "lagos-homs-ajah",
    name: "Lagos HOMS Apartment – Ajah",
    state: "Lagos", type: "Government",
    lat: 6.4675, lng: 3.5711,
    area: "Mobile Estate Rd, Ajah",
    lga: "Eti-Osa",
    unitTypes: "1, 2, 3 bed",
    status: "Completed",
    units: "84 units",
    priceRange: null,
    agency: AGENCIES.HOMS.name,
    enquiryContact: AGENCIES.HOMS,
    sourceNote: "Completed July 2020. Source: Estate Intel — publicly reported, verify before publishing."
  },
  {
    id: "lagos-igbogbo-iib",
    name: "Igbogbo IIB",
    state: "Lagos", type: "Government",
    lat: 6.6080, lng: 3.5190,
    area: "Igbogbo",
    lga: "Ikorodu",
    unitTypes: "1, 2, 3 bed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.HOMS.name,
    enquiryContact: AGENCIES.HOMS,
    sourceNote: "Source: EleniyanCares — publicly reported, verify before publishing."
  },
  {
    id: "lagos-sangotedo",
    name: "Sangotedo Scheme",
    state: "Lagos", type: "Government",
    lat: 6.4590, lng: 3.6270,
    area: "Sangotedo",
    lga: "Eti-Osa",
    unitTypes: "1, 2, 3 bed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.HOMS.name,
    enquiryContact: AGENCIES.HOMS,
    sourceNote: "Eti-Osa / Ajah axis. Source: EleniyanCares — publicly reported, verify before publishing."
  },
  {
    id: "lagos-ajara",
    name: "Ajara Estate",
    state: "Lagos", type: "Government",
    lat: 6.4130, lng: 2.8500,
    area: "Badagry",
    lga: "Badagry",
    unitTypes: "1 bed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.LAGOS_MINISTRY.name,
    enquiryContact: AGENCIES.LAGOS_MINISTRY,
    sourceNote: "Source: EleniyanCares — publicly reported, verify before publishing."
  },
  {
    id: "lagos-bayview",
    name: "Bayview Estate",
    state: "Lagos", type: "Government",
    lat: 6.4415, lng: 3.5090,
    area: "Ikate-Elegushi, Lekki",
    lga: "Eti-Osa",
    unitTypes: "Residential",
    status: "Completed",
    units: "100 units",
    priceRange: null,
    agency: AGENCIES.LAGOS_MINISTRY.name,
    enquiryContact: AGENCIES.LAGOS_MINISTRY,
    sourceNote: "Opened by Gov. Sanwo-Olu. Source: Wikipedia — publicly reported, verify before publishing."
  },
  {
    id: "lagos-gbagada",
    name: "Gbagada Housing Estate",
    state: "Lagos", type: "Government",
    lat: 6.5535, lng: 3.3880,
    area: "Gbagada",
    lga: "Kosofe",
    unitTypes: "Mixed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.LSDPC.name,
    enquiryContact: AGENCIES.LSDPC,
    sourceNote: "Existing/established. Source: Propsult — publicly reported, verify before publishing."
  },
  {
    id: "lagos-ikorodu-scheme",
    name: "Ikorodu Housing Scheme",
    state: "Lagos", type: "Government",
    lat: 6.6018, lng: 3.5106,
    area: "Ikorodu",
    lga: "Ikorodu",
    unitTypes: "Mixed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.LAGOS_MINISTRY.name,
    enquiryContact: AGENCIES.LAGOS_MINISTRY,
    sourceNote: "Existing/established. Source: Propsult — publicly reported, verify before publishing."
  },
  {
    id: "lagos-alausa",
    name: "Alausa Housing Estate",
    state: "Lagos", type: "Government",
    lat: 6.6059, lng: 3.3491,
    area: "Alausa",
    lga: "Ikeja",
    unitTypes: "Mixed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.LSDPC.name,
    enquiryContact: AGENCIES.LSDPC,
    sourceNote: "Existing/established. Source: Propsult — publicly reported, verify before publishing."
  },
  {
    id: "lagos-lekki-agbowa",
    name: "Lekki Apartments (Agbowa)",
    state: "Lagos", type: "Government",
    lat: 6.6660, lng: 3.7280,
    area: "Agbowa-Sagamu Rd",
    lga: "Ikosi-Ejirin LCDA",
    unitTypes: "48x2 bed, 24x3 bed",
    status: "Completed",
    units: "72 units (8.22 hectares)",
    priceRange: null,
    agency: AGENCIES.LSDPC.name,
    enquiryContact: AGENCIES.LSDPC,
    sourceNote: "Source: Propsult — publicly reported, verify before publishing."
  },
  {
    id: "lagos-satellite-town",
    name: "Satellite Town Estate",
    state: "Lagos", type: "Government",
    lat: 6.4633, lng: 3.2843,
    area: "Lagos-Badagry Expwy",
    lga: "Amuwo-Odofin",
    unitTypes: "Mixed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.LSDPC.name,
    enquiryContact: AGENCIES.LSDPC,
    sourceNote: "Long-established, older government estate. Source: NigerianQueries — publicly reported, verify before publishing."
  },
  {
    id: "lagos-new-homes-1250",
    name: "1,250 New Homes (multi-site)",
    state: "Lagos", type: "Government",
    lat: 6.6280, lng: 3.3460,
    area: "Multi-site: Igbogbo, Sangotedo, Iponri, Gbagada, Omole",
    lga: "Multiple LGAs",
    unitTypes: "Mixed, across 5 sites",
    status: "Announced",
    units: "1,250 units",
    priceRange: null,
    agency: AGENCIES.LAGOS_MINISTRY.name,
    enquiryContact: AGENCIES.LAGOS_MINISTRY,
    sourceNote: "Announced May 2024, 6-month target. Pin marks approximate centre of a multi-site project — not a single address. Source: Ballers.ng — verify before publishing."
  },
  {
    id: "lagos-affordable-50bn",
    name: "₦50bn Affordable Housing Scheme",
    state: "Lagos", type: "Government",
    lat: 6.6059, lng: 3.3491,
    area: "State-wide",
    lga: "State-wide",
    unitTypes: "Mixed",
    status: "Announced",
    units: "10,000 homes (target 2026)",
    priceRange: null,
    agency: AGENCIES.LAGOS_MINISTRY.name,
    enquiryContact: AGENCIES.LAGOS_MINISTRY,
    sourceNote: "Announced May 2025. Pin marks the Ministry of Housing HQ at Alausa as a symbolic location, not a project site. Source: Ballers.ng — verify before publishing."
  },
  {
    id: "lagos-renewed-hope-housing",
    name: "Renewed Hope Housing (Federal collab)",
    state: "Lagos", type: "Government",
    lat: 6.6270, lng: 3.2790,
    area: "Ipaja and Ibeju-Lekki",
    lga: "Alimosho / Ibeju-Lekki",
    unitTypes: "Mixed",
    status: "In Progress",
    units: "2,000+ units",
    priceRange: null,
    agency: AGENCIES.FMHUD.name,
    enquiryContact: AGENCIES.FMHUD,
    sourceNote: "Federal-state collaboration; additional estates planned in Badagry and Epe. Pin marks the Ipaja site. Source: Ballers.ng — verify before publishing."
  },
  {
    id: "lagos-renewed-hope-city",
    name: "Renewed Hope City Project",
    state: "Lagos", type: "Government",
    lat: 6.4459, lng: 3.9370,
    area: "Ibeju-Lekki",
    lga: "Ibeju-Lekki",
    unitTypes: "Housing units",
    status: "In Progress",
    units: "2,000 units",
    priceRange: null,
    agency: AGENCIES.FMHUD.name,
    enquiryContact: AGENCIES.FMHUD,
    sourceNote: "Construction ongoing; land provided by Lagos State. Source: FMHUD — verify before publishing."
  },

  // ---------------------------------------------------------------
  // FCT (ABUJA) — Government
  // ---------------------------------------------------------------
  {
    id: "fct-gwarinpa",
    name: "Gwarinpa Estate",
    state: "FCT", type: "Government",
    lat: 9.1000, lng: 7.4100,
    area: "Gwarinpa",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "Mixed flats/duplexes",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.FHA.name,
    enquiryContact: AGENCIES.FHA,
    sourceNote: "One of Africa's largest housing estates by plot count; developed from the 1990s in phases. Unit total unconfirmed. Source: SabiAbuja — verify before publishing."
  },
  {
    id: "fct-lugbe",
    name: "FHA Lugbe Estate",
    state: "FCT", type: "Government",
    lat: 8.9930, lng: 7.3660,
    area: "Lugbe District",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "Flats, terraces",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.FHA.name,
    enquiryContact: AGENCIES.FHA,
    sourceNote: "Source: FHA Information Memorandum, Nigeria Property Centre — verify before publishing."
  },
  {
    id: "fct-zuba",
    name: "FHA Zuba Estate",
    state: "FCT", type: "Government",
    lat: 9.1440, lng: 7.1980,
    area: "Zuba, near Zuba Model Market",
    lga: "Bwari Area Council",
    unitTypes: "1, 2 & 3 bed flats, 3 bed terrace duplex",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.FHA.name,
    enquiryContact: AGENCIES.FHA,
    sourceNote: "Units reported sold out. FHA's site separately lists a \"Zuba Mass Housing Project\" as ongoing — unclear if same or a follow-on phase. Source: FHA — verify before publishing."
  },
  {
    id: "fct-kwali",
    name: "Kwali Mass Housing Project",
    state: "FCT", type: "Government",
    lat: 8.8770, lng: 7.0140,
    area: "Kwali",
    lga: "Kwali Area Council",
    unitTypes: "Unconfirmed",
    status: "In Progress",
    units: null,
    priceRange: null,
    agency: AGENCIES.FHA.name,
    enquiryContact: AGENCIES.FHA,
    sourceNote: "Listed as ongoing on FHA's own projects page; no unit count or completion date published. Source: fha.gov.ng — verify before publishing."
  },
  {
    id: "fct-apo-hill",
    name: "Apo Hill Estate",
    state: "FCT", type: "Government",
    lat: 8.9850, lng: 7.4870,
    area: "Apo Hill",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "Unconfirmed",
    status: "In Progress",
    units: "900+ units",
    priceRange: null,
    agency: AGENCIES.FHA.name,
    enquiryContact: AGENCIES.FHA,
    sourceNote: "PPP project; groundbreaking Dec 2009, still listed as ongoing. Source: fha.gov.ng — verify before publishing."
  },
  {
    id: "fct-paradise-hills",
    name: "Paradise Hills Estate (FHA/ENL, Apo-Guzape)",
    state: "FCT", type: "Government",
    lat: 9.0080, lng: 7.5300,
    area: "Apo/Guzape, Asokoro Extension",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "2–5 bed apartments, terraces and detached/semi-detached duplexes",
    status: "In Progress",
    units: "822 planned (574 phase-1 complete, ~69%)",
    priceRange: null,
    agency: AGENCIES.FHA.name,
    enquiryContact: AGENCIES.FHA,
    sourceNote: "FHA/ENL Consortium PPP. FHA's own site cites a conflicting 932-unit figure elsewhere for \"Apo Estate\" — treat unit counts as approximate. Source: paradisehillsestate.com, fha.gov.ng — verify before publishing."
  },
  {
    id: "fct-green-city",
    name: "FHA Green City Estate",
    state: "FCT", type: "Government",
    lat: 8.9600, lng: 7.4600,
    area: "Wasa District, Apo–Wasa Expressway",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "2 bed apartments, 3 bed apartments & terrace duplex, 4 bed terrace duplex",
    status: "In Progress",
    units: "216 units (one report cites 223)",
    priceRange: null,
    agency: AGENCIES.FHA.name,
    enquiryContact: AGENCIES.FHA,
    sourceNote: "PPP with Greenpasture Dynamic Land & Homes; land allocated by FCDA. Groundbreaking 24–25 Jun 2026 — construction just started. Source: Blueprint, Pointblank News — verify before publishing."
  },
  {
    id: "fct-renewed-hope-karsana",
    name: "Renewed Hope City, Karsana",
    state: "FCT", type: "Government",
    lat: 9.1250, lng: 7.4300,
    area: "Karsana (Phase IV, near Gwarinpa/Katampe/Jahi)",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "1 bed apartments, 2 bed terraces, 3 bed flats/homes",
    status: "In Progress",
    units: "3,112 planned (~1,000 near-complete as of Nov 2024)",
    priceRange: null,
    agency: AGENCIES.FMHUD.name,
    enquiryContact: AGENCIES.FMHUD,
    sourceNote: "Part of the 100,000-unit national Renewed Hope Cities and Estates programme; FCT target is 20,000 units. Source: Housing TV Africa, renewedhopehomes.fmhud.gov.ng — verify before publishing."
  },
  {
    id: "fct-nhp-dukpai",
    name: "National Housing Programme, Dukpai",
    state: "FCT", type: "Government",
    lat: 8.9430, lng: 7.0790,
    area: "Dukpai, Gwagwalada",
    lga: "Gwagwalada Area Council",
    unitTypes: "1, 2 & 3 bed flats (3 condominium blocks)",
    status: "In Progress",
    units: "72 flats",
    priceRange: null,
    agency: AGENCIES.FMHUD.name,
    enquiryContact: AGENCIES.FMHUD,
    sourceNote: "Buhari-era National Housing Programme site; one 2020 report notes a work suspension order was issued, unclear if since resolved. Source: BusinessToday NG, Pulse Nigeria — verify before publishing."
  },
  {
    id: "fct-ahooas-idu",
    name: "AHOOAS Housing Estate, Idu (Nigerian Army)",
    state: "FCT", type: "Government",
    lat: 9.0850, lng: 7.3550,
    area: "Idu",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "Flats (100 blocks of 4)",
    status: "Completed",
    units: "400 units",
    priceRange: null,
    agency: AGENCIES.FMHUD.name,
    enquiryContact: AGENCIES.FMHUD,
    sourceNote: "Built for injured soldiers and personnel; commissioned 18 Dec 2024. Federal (Nigerian Army), not FHA/FCDA. Source: Leadership NG — verify before publishing."
  },
  {
    id: "fct-bungalow-city",
    name: "Bungalow City",
    state: "FCT", type: "Government",
    lat: 9.1200, lng: 7.2500,
    area: "Dei-Dei–Zuba Expressway",
    lga: "Bwari Area Council",
    unitTypes: "2 bed detached, 3 bed terrace",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.FMBN.name,
    enquiryContact: AGENCIES.FMBN,
    sourceNote: "NHF Rent-to-Own scheme; FMBN financed, built by Brains and Hammers. Handed over 23–24 Jun 2026. Source: News Chronicle, Housing TV Africa — verify before publishing."
  },
  {
    id: "fct-prince-princess",
    name: "Prince & Princess Mass Housing Estate",
    state: "FCT", type: "Government",
    lat: 9.0500, lng: 7.4700,
    area: "Duboyi District",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.FCDA.name,
    enquiryContact: AGENCIES.FCDA,
    sourceNote: "Delivered under FCDA's Mass Housing PPP framework; FCDA notes it needs infrastructure upgrades. Source: fcda.gov.ng — verify before publishing."
  },
  {
    id: "fct-jubilation-court",
    name: "Jubilation Court Estate",
    state: "FCT", type: "Government",
    lat: 8.9950, lng: 7.4500,
    area: "Dakwo District",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.FCDA.name,
    enquiryContact: AGENCIES.FCDA,
    sourceNote: "FCDA Mass Housing PPP, developer Crystal-Link Aluminum Products Ltd. Source: fcda.gov.ng — verify before publishing."
  },
  {
    id: "fct-jubilation-bethel",
    name: "Jubilation Bethel Estate",
    state: "FCT", type: "Government",
    lat: 8.9900, lng: 7.4550,
    area: "Lokogoma District",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.FCDA.name,
    enquiryContact: AGENCIES.FCDA,
    sourceNote: "FCDA Mass Housing PPP, developer Nemmacol Nigeria Ltd. Source: fcda.gov.ng — verify before publishing."
  },
  {
    id: "fct-frsc-lokogoma",
    name: "FRSC Staff Housing Estate",
    state: "FCT", type: "Government",
    lat: 8.9900, lng: 7.4550,
    area: "Lokogoma District",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.FCDA.name,
    enquiryContact: AGENCIES.FCDA,
    sourceNote: "FCDA Mass Housing PPP, FRSC Staff Housing Co-operative Society. Source: fcda.gov.ng — verify before publishing."
  },
  {
    id: "fct-katampe-ppp",
    name: "Katampe District PPP Housing Scheme",
    state: "FCT", type: "Government",
    lat: 9.1100, lng: 7.4450,
    area: "Katampe District",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "Unconfirmed",
    status: "In Progress",
    units: null,
    priceRange: null,
    agency: AGENCIES.FCDA.name,
    enquiryContact: AGENCIES.FCDA,
    sourceNote: "Reported ~23.5% complete, work suspended; developer Deanshanger Projects Ltd, ₦61.19bn project cost. Source: fcda.gov.ng — verify before publishing."
  },
  {
    id: "fct-mabushi-ppp",
    name: "Mabushi District PPP Housing Scheme",
    state: "FCT", type: "Government",
    lat: 9.0850, lng: 7.4350,
    area: "Mabushi District",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "Unconfirmed",
    status: "Announced",
    units: null,
    priceRange: null,
    agency: AGENCIES.FCDA.name,
    enquiryContact: AGENCIES.FCDA,
    sourceNote: "Preferred bidder selected; build-out progress unconfirmed. Source: fcda.gov.ng — verify before publishing."
  },
  {
    id: "fct-kado",
    name: "FHA Kado Estate",
    state: "FCT", type: "Government",
    lat: 9.0800, lng: 7.4200,
    area: "Kado, near Jabi Lake",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "Mixed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.FHA.name,
    enquiryContact: AGENCIES.FHA,
    sourceNote: "Source: SabiAbuja — verify before publishing."
  },
  {
    id: "fct-kubwa",
    name: "FHA Kubwa Housing Scheme",
    state: "FCT", type: "Government",
    lat: 9.1580, lng: 7.3320,
    area: "Kubwa (Phase 2, Phase 3)",
    lga: "Bwari Area Council",
    unitTypes: "Mixed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.FHA.name,
    enquiryContact: AGENCIES.FHA,
    sourceNote: "Source: SabiAbuja — verify before publishing."
  },

  // ---------------------------------------------------------------
  // RIVERS STATE — Government
  // ---------------------------------------------------------------
  {
    id: "rv-greater-taf-city",
    name: "Greater TAF City",
    state: "Rivers", type: "Government",
    lat: 4.8600, lng: 7.0100,
    area: "Obirikwere, Airport Road",
    lga: "Obio/Akpor",
    unitTypes: "2 bed bungalows to 4 bed duplexes",
    status: "In Progress",
    units: "20,000 planned (Phase 1: 1,000 units, commissioned Dec 2025)",
    priceRange: null,
    agency: "Rivers State Government + TAF Africa Global (Greater PH City Development Authority + Pricewise Homes)",
    enquiryContact: AGENCIES.RIVERS_GOVT,
    sourceNote: "Rivers State-led PPP, rhetorically tied to but distinct from FHA's federal Renewed Hope programme. Source: The Nation, Hallmark News — verify before publishing."
  },
  {
    id: "rv-ph-airportcity",
    name: "Port Harcourt AirportCity",
    state: "Rivers", type: "Government",
    lat: 4.9930, lng: 6.9490,
    area: "Omagwa, near PH International Airport",
    lga: "Ikwerre",
    unitTypes: "1–5 bed \"smart homes\"",
    status: "Announced",
    units: "2,000 planned (initial phase)",
    priceRange: null,
    agency: "Rivers State Government (via GPCDA, 30%) + Masta Services Ltd (70%)",
    enquiryContact: AGENCIES.RIVERS_GOVT,
    sourceNote: "Partnership signed 2025; 80-hectare site. Source: Guardian Nigeria, PropertyAccess.ng — verify before publishing."
  },
  {
    id: "rv-iriebe",
    name: "Iriebe Housing Estate",
    state: "Rivers", type: "Government",
    lat: 4.8700, lng: 7.0700,
    area: "Off Aba Expressway",
    lga: "Obio/Akpor",
    unitTypes: "2 & 3 bed bungalows, 1 & 2 bed flats",
    status: "In Progress",
    units: "834 planned (300+ occupied as of 2014 — figure likely stale)",
    priceRange: null,
    agency: AGENCIES.RSHPDA.name,
    enquiryContact: AGENCIES.RSHPDA,
    sourceNote: "Financed with FMBN/NHF support; most recent public occupancy figure found dates to 2014. Source: The Tide — verify before publishing, occupancy likely higher now."
  },
  {
    id: "rv-fha-trans-amadi",
    name: "FHA Estate, Old Trans-Amadi/Rumueme",
    state: "Rivers", type: "Government",
    lat: 4.7900, lng: 7.0350,
    area: "Trans-Amadi / Rumueme",
    lga: "Port Harcourt City",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: "207 units",
    priceRange: null,
    agency: AGENCIES.FHA.name,
    enquiryContact: AGENCIES.FHA,
    sourceNote: "Allocated on mortgage terms 1987/1990. Source: fha.gov.ng/past-projects — verify before publishing."
  },
  {
    id: "rv-elekahia",
    name: "Elekahia Housing Estate",
    state: "Rivers", type: "Government",
    lat: 4.8000, lng: 7.0450,
    area: "Elekahia",
    lga: "Obio/Akpor",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.RSHPDA.name,
    enquiryContact: AGENCIES.RSHPDA,
    sourceNote: "Existing/legacy estate; RSHPDA lists it by name only, no unit count published. Source: rshpda.gov.ng — verify before publishing."
  },
  {
    id: "rv-rumuibekwe",
    name: "Rumuibekwe Housing Estate",
    state: "Rivers", type: "Government",
    lat: 4.8500, lng: 7.0200,
    area: "Rumuibekwe",
    lga: "Obio/Akpor",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.RSHPDA.name,
    enquiryContact: AGENCIES.RSHPDA,
    sourceNote: "Existing/legacy estate; RSHPDA lists it by name only, no unit count published. Source: rshpda.gov.ng — verify before publishing."
  },
  {
    id: "rv-rumuobiakani",
    name: "Rumuobiakani Housing Estate",
    state: "Rivers", type: "Government",
    lat: 4.8450, lng: 7.0150,
    area: "Rumuobiakani",
    lga: "Obio/Akpor",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.RSHPDA.name,
    enquiryContact: AGENCIES.RSHPDA,
    sourceNote: "Existing/legacy estate; RSHPDA lists it by name only, no unit count published. Source: rshpda.gov.ng — verify before publishing."
  },
  {
    id: "rv-abuloma",
    name: "Abuloma Housing Estate (Phases I–III)",
    state: "Rivers", type: "Government",
    lat: 4.7600, lng: 7.0450,
    area: "Abuloma waterfront",
    lga: "Port Harcourt City",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.RSHPDA.name,
    enquiryContact: AGENCIES.RSHPDA,
    sourceNote: "Existing/legacy estate; RSHPDA lists it by name only, no unit count published. Source: rshpda.gov.ng — verify before publishing."
  },
  {
    id: "rv-presidential",
    name: "Presidential Housing Estate",
    state: "Rivers", type: "Government",
    lat: 4.8156, lng: 7.0300,
    area: "Port Harcourt (exact sub-area unconfirmed)",
    lga: "Port Harcourt City",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.RSHPDA.name,
    enquiryContact: AGENCIES.RSHPDA,
    sourceNote: "Existing/legacy estate; RSHPDA lists it by name only, no unit count published, location approximate. Source: rshpda.gov.ng — verify before publishing."
  },
  {
    id: "rv-ndoki",
    name: "Ndoki Waterfront Estate",
    state: "Rivers", type: "Government",
    lat: 4.7700, lng: 7.0500,
    area: "Port Harcourt waterfront (exact sub-area unconfirmed)",
    lga: "Port Harcourt City",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.RSHPDA.name,
    enquiryContact: AGENCIES.RSHPDA,
    sourceNote: "Existing/legacy estate; RSHPDA lists it by name only, no unit count published, location approximate. Source: rshpda.gov.ng — verify before publishing."
  },
  {
    id: "rv-aggrey",
    name: "Aggrey Waterfront Estate",
    state: "Rivers", type: "Government",
    lat: 4.7850, lng: 7.0250,
    area: "Aggrey Road axis",
    lga: "Port Harcourt City",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.RSHPDA.name,
    enquiryContact: AGENCIES.RSHPDA,
    sourceNote: "Existing/legacy estate; RSHPDA lists it by name only, no unit count published. Source: rshpda.gov.ng — verify before publishing."
  },
  {
    id: "rv-marine-base",
    name: "Marine Base Waterfront Estate",
    state: "Rivers", type: "Government",
    lat: 4.7750, lng: 7.0150,
    area: "Marine Base",
    lga: "Port Harcourt City",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.RSHPDA.name,
    enquiryContact: AGENCIES.RSHPDA,
    sourceNote: "Existing/legacy estate; RSHPDA lists it by name only, no unit count published. Source: rshpda.gov.ng — verify before publishing."
  },
  {
    id: "rv-diobu",
    name: "Diobu Housing Estate (Mile I, II, III)",
    state: "Rivers", type: "Government",
    lat: 4.8100, lng: 6.9950,
    area: "Diobu",
    lga: "Port Harcourt City",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.RSHPDA.name,
    enquiryContact: AGENCIES.RSHPDA,
    sourceNote: "Existing/legacy estate. Source: National Network — verify before publishing."
  },
  {
    id: "rv-ph-township",
    name: "Port Harcourt Township Housing Estate",
    state: "Rivers", type: "Government",
    lat: 4.7800, lng: 7.0100,
    area: "Old Township area",
    lga: "Port Harcourt City",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.RSHPDA.name,
    enquiryContact: AGENCIES.RSHPDA,
    sourceNote: "Existing/legacy estate. Source: National Network — verify before publishing."
  },
  {
    id: "rv-rumuomasi",
    name: "Rumuomasi Housing Estate",
    state: "Rivers", type: "Government",
    lat: 4.8250, lng: 7.0300,
    area: "Rumuomasi",
    lga: "Obio/Akpor",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.RSHPDA.name,
    enquiryContact: AGENCIES.RSHPDA,
    sourceNote: "Existing/legacy estate. Source: National Network — verify before publishing."
  },
  {
    id: "rv-rainbow-town",
    name: "Rainbow Town",
    state: "Rivers", type: "Government",
    lat: 4.7950, lng: 7.0400,
    area: "Trans Amadi",
    lga: "Port Harcourt City",
    unitTypes: "Apartments, terraces, duplexes, penthouses",
    status: "In Progress",
    units: "~1,181 planned",
    priceRange: null,
    agency: "Rivers State Government + First Bank Nigeria (JV: CityScape International Development Plc)",
    enquiryContact: AGENCIES.RIVERS_GOVT,
    sourceNote: "Public-private JV, not a purely private development. Detached houses/terraces completed 2015; tower phases reportedly stalled since. Source: Estate Intel, BusinessDay archive — verify before publishing."
  },

  // ---------------------------------------------------------------
  // PRIVATE ESTATES — seed set (developer self-submission planned;
  // these were sourced from public listings/aggregators in the meantime)
  // ---------------------------------------------------------------
  {
    id: "pv-lekki-gardens",
    name: "Lekki Gardens Estate",
    state: "Lagos", type: "Private",
    lat: 6.4650, lng: 3.5900,
    area: "Ajah / Lekki Peninsula II",
    lga: "Eti-Osa",
    unitTypes: "2–4 bed terrace duplexes, flats",
    status: "In Progress",
    units: null,
    priceRange: "₦27M – ₦650M (avg ~₦120M)",
    agency: "Lekki Gardens Homes & Properties Ltd (private developer)",
    enquiryContact: { name: "Lekki Gardens Homes & Properties Ltd", phone: null, email: null, website: "https://lekkigardens.com/" },
    sourceNote: "Phased development, some phases complete, others still selling. Source: PropertyPro.ng, lekkigardens.com — verify before publishing."
  },
  {
    id: "pv-pinnock-beach",
    name: "Pinnock Beach Estate",
    state: "Lagos", type: "Private",
    lat: 6.4460, lng: 3.5280,
    area: "Osapa, Lekki",
    lga: "Eti-Osa",
    unitTypes: "Duplexes, land plots",
    status: "Completed",
    units: null,
    priceRange: "₦125M – ₦4B (avg ~₦1.5B)",
    agency: "UPDC (UAC of Nigeria Plc subsidiary)",
    enquiryContact: { name: "UPDC Plc", phone: null, email: null, website: "https://nigeriapropertycentre.com/for-sale/houses/lagos/lekki/osapa/showtype?n=pinnock+beach+estate" },
    sourceNote: "Source: NigeriaPropertyCentre — verify before publishing."
  },
  {
    id: "pv-megamound",
    name: "Megamound Estate",
    state: "Lagos", type: "Private",
    lat: 6.4500, lng: 3.5500,
    area: "Lekki",
    lga: "Eti-Osa",
    unitTypes: "Duplexes, flats",
    status: "In Progress",
    units: null,
    priceRange: "₦50M – ₦1.5B (avg ~₦420M)",
    agency: "Megamound Real Estate & Construction Group",
    enquiryContact: { name: "Megamound Real Estate & Construction Group", phone: null, email: null, website: "https://megamound.com/" },
    sourceNote: "Source: megamound.com, NigeriaPropertyCentre — verify before publishing."
  },
  {
    id: "pv-northern-foreshore",
    name: "Northern Foreshore Estate",
    state: "Lagos", type: "Private",
    lat: 6.4430, lng: 3.5350,
    area: "Osapa / Chevron, Lekki",
    lga: "Eti-Osa",
    unitTypes: "Duplexes, land",
    status: "In Progress",
    units: null,
    priceRange: "Price on request",
    agency: "Aircom Nigeria",
    enquiryContact: { name: "Aircom Nigeria", phone: null, email: null, website: "http://www.aircomng.com/northern-foreshore/" },
    sourceNote: "Source: aircomng.com, Estate Intel — verify before publishing."
  },
  {
    id: "pv-alaro-city",
    name: "Alaro City (Universal Homes phase)",
    state: "Lagos", type: "Private",
    lat: 6.4550, lng: 3.7100,
    area: "Lekki Free Zone, Epe",
    lga: "Ibeju-Lekki",
    unitTypes: "2 bed apartments and up",
    status: "In Progress",
    units: "Phase 1: ~576 units, due end 2026",
    priceRange: "From $79,950",
    agency: "Rendeavour / Universal Homes",
    enquiryContact: { name: "Alaro City / Rendeavour", phone: null, email: null, website: "https://www.alarocity.com/now-selling/homes/" },
    sourceNote: "Source: alarocity.com, BusinessDay — verify before publishing."
  },
  {
    id: "pv-brains-hammers",
    name: "Brains and Hammers Estate",
    state: "FCT", type: "Private",
    lat: 9.1000, lng: 7.4300,
    area: "Life Camp / Katampe / Jabi corridor",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "Duplexes, terraces, flats",
    status: "In Progress",
    units: null,
    priceRange: "₦60M – ₦380M (avg ~₦80M)",
    agency: "Brains and Hammers Ltd",
    enquiryContact: { name: "Brains and Hammers Ltd", phone: null, email: null, website: "https://brainsandhammers.com/" },
    sourceNote: "Source: brainsandhammers.com, NigeriaPropertyCentre — verify before publishing."
  },
  {
    id: "pv-trademore",
    name: "Trademore Estate",
    state: "FCT", type: "Private",
    lat: 8.9850, lng: 7.3600,
    area: "Lugbe District",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "Terrace, semi-detached, detached duplexes",
    status: "Completed",
    units: null,
    priceRange: "₦6M – ₦16M+ (listing appears dated)",
    agency: "Trademore International Holdings Ltd",
    enquiryContact: { name: "Trademore International Holdings Ltd", phone: null, email: null, website: "https://trademoreestates.com/" },
    sourceNote: "Estate was affected by a notable flood event in 2022. Price figures read as several years old — treat as indicative only. Source: trademoreestates.com, NigeriaPropertyCentre — verify before publishing."
  },
  {
    id: "pv-efab-city",
    name: "Efab City Estate",
    state: "FCT", type: "Private",
    lat: 9.0900, lng: 7.4150,
    area: "Mbora District",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "Flats, duplexes, bungalows, condos",
    status: "In Progress",
    units: null,
    priceRange: "₦75M – ₦130M+",
    agency: "Efab Properties",
    enquiryContact: { name: "Efab Properties", phone: null, email: null, website: "https://efabproperties.com/efabproperties/estates/efab-city-estate-mbora-district/index.html" },
    sourceNote: "Source: efabproperties.com — verify before publishing."
  },
  {
    id: "pv-cosgrove-guzape",
    name: "Cosgrove Smart Estate",
    state: "FCT", type: "Private",
    lat: 9.0100, lng: 7.5250,
    area: "Guzape",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "7 bed smart villas",
    status: "In Progress",
    units: "5 units",
    priceRange: "Price on request",
    agency: "Cosgrove Investment Ltd (Cosgrove Africa)",
    enquiryContact: { name: "Cosgrove Africa", phone: null, email: null, website: "https://cosgroveafrica.com/projects/cosgrove_smart_estate_guzape" },
    sourceNote: "Boutique/luxury scale — 5 units, smaller than a typical estate. Source: cosgroveafrica.com — verify before publishing."
  },
  {
    id: "pv-garden-heights",
    name: "Garden Heights Estate",
    state: "Rivers", type: "Private",
    lat: 4.8250, lng: 7.0250,
    area: "GRA Phase III",
    lga: "Port Harcourt City",
    unitTypes: "Studio, 1–3 bed apartments, semi-detached bungalows, detached duplexes",
    status: "In Progress",
    units: "Scheme 1: ~24 units; ~600 planned across 4 schemes",
    priceRange: "Price on request",
    agency: "Port Harcourt Gardens Limited (PGL)",
    enquiryContact: { name: "Port Harcourt Gardens Limited", phone: null, email: null, website: "https://guardian.ng/property/developer-unveils-port-harcourts-garden-heights-estate/" },
    sourceNote: "Source: The Guardian Nigeria — verify before publishing."
  },
  {
    id: "pv-suncity-gardens",
    name: "Suncity Gardens Estate",
    state: "Rivers", type: "Private",
    lat: 4.8350, lng: 7.0450,
    area: "Peter Odili Road",
    lga: "Obio/Akpor",
    unitTypes: "Studio, 2–3 bed apartments, 4 bed terrace, 5 bed duplex",
    status: "In Progress",
    units: null,
    priceRange: "From ₦7M (listing appears dated, ~2021)",
    agency: "Suncity Gardens Estate Ltd",
    enquiryContact: { name: "Suncity Gardens Estate Ltd", phone: null, email: null, website: "https://suncitygarden.org/" },
    sourceNote: "Pricing likely stale. Source: suncitygarden.org — verify before publishing."
  },

  // ---------------------------------------------------------------
  // OGUN STATE — Government
  // ---------------------------------------------------------------
  {
    id: "og-prince-court-ph1",
    name: "Prince Court Estate (Phase 1)",
    state: "Ogun", type: "Government",
    lat: 7.1300, lng: 3.3800,
    area: "Kemta, Idi-Aba, Abeokuta",
    lga: "Abeokuta South",
    unitTypes: "2 bed (80) & 3 bed (20) detached bungalows",
    status: "Completed",
    units: "100 units",
    priceRange: null,
    agency: AGENCIES.OGSHC.name,
    enquiryContact: AGENCIES.OGSHC,
    sourceNote: "Source: ogshc.og.gov.ng — verify before publishing."
  },
  {
    id: "og-prince-court-ph3",
    name: "Prince Court Estate (Phase 3)",
    state: "Ogun", type: "Government",
    lat: 7.1310, lng: 3.3790,
    area: "Kemta, Idi-Aba, Abeokuta",
    lga: "Abeokuta South",
    unitTypes: "Detached / semi-detached",
    status: "In Progress",
    units: null,
    priceRange: null,
    agency: AGENCIES.OGSHC.name,
    enquiryContact: AGENCIES.OGSHC,
    sourceNote: "Under construction, now selling. Source: ogshc.og.gov.ng — verify before publishing."
  },
  {
    id: "og-prince-court-kobape",
    name: "Prince Court Estate, Kobape",
    state: "Ogun", type: "Government",
    lat: 7.0750, lng: 3.4550,
    area: "Kobape, Siun-Sagamu Expressway",
    lga: "Odeda",
    unitTypes: "Mixed",
    status: "In Progress",
    units: "~527 units (single-source, unconfirmed)",
    priceRange: null,
    agency: AGENCIES.OGSHC.name + " / " + AGENCIES.OPIC.name,
    enquiryContact: AGENCIES.OGSHC,
    sourceNote: "Unit figure from a single source (People's Voice, Jan 2026), could not be cross-verified — treat as low confidence."
  },
  {
    id: "og-prince-court-sagamu",
    name: "Prince Court Estate, Sagamu",
    state: "Ogun", type: "Government",
    lat: 6.8480, lng: 3.6490,
    area: "Sagamu",
    lga: "Sagamu",
    unitTypes: "Low-cost housing",
    status: "Announced",
    units: "~200 units (part of a 500-unit, 3-site programme)",
    priceRange: null,
    agency: "Ogun State Government",
    enquiryContact: AGENCIES.OGSHC,
    sourceNote: "Announced/inaugurated 2024 alongside Ilaro and Ijebu-Ode sites. Source: The Sun — verify before publishing."
  },
  {
    id: "og-prince-court-itanrin",
    name: "Prince Court Estate, Itanrin",
    state: "Ogun", type: "Government",
    lat: 6.8250, lng: 3.9200,
    area: "Itanrin, Ijebu-Ode",
    lga: "Ijebu-Ode",
    unitTypes: "Low-cost housing",
    status: "Announced",
    units: "~200 units (part of a 500-unit, 3-site programme)",
    priceRange: null,
    agency: "Ogun State Government",
    enquiryContact: AGENCIES.OGSHC,
    sourceNote: "Announced/inaugurated 2024. Source: The Sun — verify before publishing."
  },
  {
    id: "og-prince-court-ilaro",
    name: "Prince Court Estate, Ilaro",
    state: "Ogun", type: "Government",
    lat: 6.8890, lng: 3.0280,
    area: "Ilaro",
    lga: "Yewa South",
    unitTypes: "Low-cost housing",
    status: "Announced",
    units: "~100 units (part of a 500-unit, 3-site programme)",
    priceRange: null,
    agency: "Ogun State Government",
    enquiryContact: AGENCIES.OGSHC,
    sourceNote: "Announced/inaugurated 2024. Source: The Sun — verify before publishing."
  },
  {
    id: "og-pmb-estate",
    name: "PMB (President Muhammadu Buhari) Estate",
    state: "Ogun", type: "Government",
    lat: 7.0800, lng: 3.4600,
    area: "Kobape Road, off Sagamu Expressway, Abeokuta",
    lga: "Odeda",
    unitTypes: "4 bed detached/semi-detached duplexes",
    status: "In Progress",
    units: "250 planned (~80% complete)",
    priceRange: null,
    agency: AGENCIES.OPIC.name,
    enquiryContact: AGENCIES.OPIC,
    sourceNote: "Targeted for completion end-2023, still selling as of Aug 2024. Source: Daily Post, pmbestate.com.ng — verify before publishing."
  },
  {
    id: "og-kobape-phase-iii",
    name: "Kobape Phase III Low-Cost Housing Scheme",
    state: "Ogun", type: "Government",
    lat: 7.0850, lng: 3.4650,
    area: "Kobape, Abeokuta–Sagamu Expressway",
    lga: "Odeda",
    unitTypes: "2 bedroom",
    status: "In Progress",
    units: "224 units targeted (allocation began Jun 2024)",
    priceRange: null,
    agency: "Ogun State Ministry of Housing",
    enquiryContact: AGENCIES.OGSHC,
    sourceNote: "Source: BusinessDay, The Sun — verify before publishing."
  },
  {
    id: "og-kings-court",
    name: "Kings Court Estate",
    state: "Ogun", type: "Government",
    lat: 7.1550, lng: 3.3500,
    area: "Oke-Mosan / Warewa, Abeokuta",
    lga: "Abeokuta South",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: "200 units (single-source, Warewa)",
    priceRange: null,
    agency: AGENCIES.OGSHC.name + " / " + AGENCIES.OPIC.name,
    enquiryContact: AGENCIES.OGSHC,
    sourceNote: "Source: THISDAY/Punch, Oct 2025 — verify before publishing."
  },
  {
    id: "og-gateway-aviation-village",
    name: "Gateway Aviation Village",
    state: "Ogun", type: "Government",
    lat: 6.8950, lng: 3.7150,
    area: "Iperu, Ikenne LGA",
    lga: "Ikenne",
    unitTypes: "2 bed expandable bungalows",
    status: "In Progress",
    units: "200 units",
    priceRange: null,
    agency: "Ogun State Government",
    enquiryContact: AGENCIES.OGSHC,
    sourceNote: "Construction began Sept 2023. Source: Daily Post — verify before publishing."
  },
  {
    id: "og-hid-awolowo",
    name: "H.I.D. Awolowo Estate",
    state: "Ogun", type: "Government",
    lat: 7.1200, lng: 3.4200,
    area: "Presidential Boulevard, Obasanjo Hilltop, Abeokuta",
    lga: "Abeokuta South",
    unitTypes: "2/3 bed semi-detached bungalows, 3 bed detached, 4 bed duplexes, 2/3 bed flats",
    status: "Completed",
    units: "82 units",
    priceRange: null,
    agency: AGENCIES.OGSHC.name,
    enquiryContact: AGENCIES.OGSHC,
    sourceNote: "Commissioned 2015. Source: ogshc.og.gov.ng — verify before publishing."
  },
  {
    id: "og-aak-degun-mitros",
    name: "A.A.K. Degun Mitros Estate",
    state: "Ogun", type: "Government",
    lat: 7.1600, lng: 3.3400,
    area: "Laderin, Abeokuta",
    lga: "Abeokuta North",
    unitTypes: "2 bed flats, 2 bed semi-detached, 3 bed semi-detached",
    status: "Completed",
    units: "118 units (Phase 1)",
    priceRange: null,
    agency: AGENCIES.OGSHC.name,
    enquiryContact: AGENCIES.OGSHC,
    sourceNote: "Completed 2015. Source: ogshc.og.gov.ng — verify before publishing."
  },
  {
    id: "og-presidential-mandate",
    name: "Presidential Mandate Estate",
    state: "Ogun", type: "Government",
    lat: 7.1210, lng: 3.4210,
    area: "Obasanjo Hilltop, Abeokuta",
    lga: "Abeokuta South",
    unitTypes: "Interlocking-brick bungalows",
    status: "Completed",
    units: "100 units",
    priceRange: null,
    agency: AGENCIES.OGSHC.name,
    enquiryContact: AGENCIES.OGSHC,
    sourceNote: "Source: ogshc.og.gov.ng — verify before publishing."
  },
  {
    id: "og-ibara-estate",
    name: "Ibara Estate (Ibara GRA)",
    state: "Ogun", type: "Government",
    lat: 7.1550, lng: 3.3550,
    area: "Ibara, Abeokuta",
    lga: "Abeokuta South",
    unitTypes: "3 bed bungalows with garage",
    status: "Completed",
    units: "370 units (original)",
    priceRange: null,
    agency: AGENCIES.OGSHC.name,
    enquiryContact: AGENCIES.OGSHC,
    sourceNote: "Legacy estate built 1976–78; now under a state urban-renewal/regeneration scheme. Source: locatelord.com, OGSHC — verify before publishing."
  },
  {
    id: "og-the-havens",
    name: "The Havens",
    state: "Ogun", type: "Government",
    lat: 6.8300, lng: 3.9300,
    area: "Igbeba, Ijebu-Ode",
    lga: "Ijebu-Ode",
    unitTypes: "4 & 5 bed detached duplexes with BQ",
    status: "In Progress",
    units: null,
    priceRange: null,
    agency: AGENCIES.OGSHC.name,
    enquiryContact: AGENCIES.OGSHC,
    sourceNote: "Under construction, now selling. Source: ogshc.og.gov.ng — verify before publishing."
  },
  {
    id: "og-ota-estate",
    name: "Ota Residential & Industrial Estate",
    state: "Ogun", type: "Government",
    lat: 6.6800, lng: 3.2350,
    area: "Ota",
    lga: "Ado-Odo/Ota",
    unitTypes: "Mixed residential + industrial plots",
    status: "In Progress",
    units: "Plot-based (4,000–4,500 sqm plots)",
    priceRange: null,
    agency: AGENCIES.OGSHC.name,
    enquiryContact: AGENCIES.OGSHC,
    sourceNote: "Land sales ongoing. Source: ogshc.og.gov.ng — verify before publishing."
  },
  {
    id: "og-fha-gateway",
    name: "FHA Gateway Estate",
    state: "Ogun", type: "Government",
    lat: 6.9200, lng: 3.4300,
    area: "Ofada, Obafemi Owode LGA",
    lga: "Obafemi Owode",
    unitTypes: "2 bed apartments (95), 3 bed terrace duplexes (100)",
    status: "In Progress",
    units: "195 units",
    priceRange: null,
    agency: AGENCIES.FHA.name,
    enquiryContact: AGENCIES.FHA,
    sourceNote: "PPP with Greenpasture Homes & Akkenog International; groundbreaking May 2026. Source: Tribune, Vanguard, Leadership — verify before publishing."
  },
  {
    id: "og-renewed-hope-abeokuta",
    name: "Renewed Hope Housing Scheme (Abeokuta 1 & 2)",
    state: "Ogun", type: "Government",
    lat: 7.0820, lng: 3.4620,
    area: "PMB Estate site, Kobape Road, Abeokuta",
    lga: "Odeda",
    unitTypes: "Detached & semi-detached duplexes",
    status: "In Progress",
    units: "Min. 250 units per site nationally (Ogun-specific count unconfirmed)",
    priceRange: null,
    agency: AGENCIES.FMHUD.name,
    enquiryContact: AGENCIES.FMHUD,
    sourceNote: "Part of a nationwide 30-state, 1-estate Renewed Hope programme. Source: ThisDay, renewedhopehomes.fmhud.gov.ng — verify before publishing."
  },

  // ---------------------------------------------------------------
  // KANO STATE — Government
  // ---------------------------------------------------------------
  {
    id: "kn-family-homes-darmanawa",
    name: "Family Homes Estate, Darmanawa",
    state: "Kano", type: "Government",
    lat: 11.9700, lng: 8.5450,
    area: "Darmanawa, Tarauni LGA",
    lga: "Tarauni",
    unitTypes: "2 bed flats, 3 bed bungalows",
    status: "Completed",
    units: "500 built (469 families at commissioning)",
    priceRange: null,
    agency: AGENCIES.FHFL.name,
    enquiryContact: AGENCIES.FHFL,
    sourceNote: "Commissioned by Pres. Buhari, 30 Jan 2023. Source: Vanguard, Guardian, fhfl.com.ng — verify before publishing."
  },
  {
    id: "kn-renewed-hope-janguza",
    name: "Renewed Hope City, Janguza",
    state: "Kano", type: "Government",
    lat: 12.1800, lng: 8.4200,
    area: "Gidanka/Garkuwarka, Janguza, near Lambu",
    lga: "Tofa",
    unitTypes: "1 bed semi-det. bungalow (100), 2 bed semi-det. bungalow (300), 3 bed bungalow (100)",
    status: "In Progress",
    units: "500 units",
    priceRange: null,
    agency: AGENCIES.FMHUD.name,
    enquiryContact: AGENCIES.FMHUD,
    sourceNote: "Groundbreaking 23 Mar 2024; financed by FHFL, built by CCGCC. Source: Nairametrics, fmhud.gov.ng — verify before publishing."
  },
  {
    id: "kn-gida-gida",
    name: "Gida-Gida Mega City",
    state: "Kano", type: "Government",
    lat: 11.8900, lng: 8.7200,
    area: "Rijiyar Gwan-Gwan, Dawakin Kudu LGA",
    lga: "Dawakin Kudu",
    unitTypes: "Unconfirmed",
    status: "Announced",
    units: "480 units (₦113.193bn approved)",
    priceRange: null,
    agency: AGENCIES.KANO_GOVT.name,
    enquiryContact: AGENCIES.KANO_GOVT,
    sourceNote: "Approved by executive council 12 Mar 2026. Source: New Telegraph, Daily Trust — verify before publishing."
  },
  {
    id: "kn-kwankwasiyya-city",
    name: "Kwankwasiyya City",
    state: "Kano", type: "Government",
    lat: 11.9200, lng: 8.4900,
    area: "Kumbotso axis (satellite town)",
    lga: "Kumbotso",
    unitTypes: "Mixed residential",
    status: "In Progress",
    units: "~1,600–3,200 planned across 3 satellite cities; 324 units taken over from pension trustees 2024",
    priceRange: null,
    agency: AGENCIES.KANO_GOVT.name,
    enquiryContact: AGENCIES.KANO_GOVT,
    sourceNote: "Ongoing since 2012; one of 3 linked satellite-city projects (with Amana and Bandirawo). Source: TheCable, kanostate.gov.ng — verify before publishing."
  },
  {
    id: "kn-amana-city",
    name: "Amana City",
    state: "Kano", type: "Government",
    lat: 11.9350, lng: 8.5000,
    area: "Satellite town",
    lga: "Kumbotso",
    unitTypes: "Mixed residential",
    status: "In Progress",
    units: "Shares planned total with Kwankwasiyya & Bandirawo",
    priceRange: null,
    agency: AGENCIES.KANO_GOVT.name,
    enquiryContact: AGENCIES.KANO_GOVT,
    sourceNote: "Ongoing since 2012, part of the same 3-city programme. Source: kanostate.gov.ng — verify before publishing."
  },
  {
    id: "kn-bandirawo-city",
    name: "Bandirawo City",
    state: "Kano", type: "Government",
    lat: 11.9450, lng: 8.4950,
    area: "Satellite town",
    lga: "Kumbotso",
    unitTypes: "Mixed residential",
    status: "In Progress",
    units: "Shares planned total with Kwankwasiyya & Amana",
    priceRange: null,
    agency: AGENCIES.KANO_GOVT.name,
    enquiryContact: AGENCIES.KANO_GOVT,
    sourceNote: "Ongoing since 2012, part of the same 3-city programme. Source: kanostate.gov.ng — verify before publishing."
  },
  {
    id: "kn-sharada",
    name: "Sharada Estate",
    state: "Kano", type: "Government",
    lat: 11.9700, lng: 8.5100,
    area: "Sharada",
    lga: "Kano Municipal",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: "178 units",
    priceRange: null,
    agency: AGENCIES.FHA.name,
    enquiryContact: AGENCIES.FHA,
    sourceNote: "Commissioned 1998, mortgage allocation. Source: fha.gov.ng/past-projects — verify before publishing."
  },
  {
    id: "kn-mariri",
    name: "Mariri Estate",
    state: "Kano", type: "Government",
    lat: 12.0200, lng: 8.5700,
    area: "Mariri",
    lga: "Kano Municipal",
    unitTypes: "National Housing Programme type",
    status: "In Progress",
    units: "970 planned, reported uncompleted",
    priceRange: null,
    agency: AGENCIES.FHA.name + " (transferred to Kano State Govt)",
    enquiryContact: AGENCIES.FHA,
    sourceNote: "Sold to Kano State Govt 1993, remained uncompleted. Source: fha.gov.ng/past-projects — verify before publishing."
  },
  {
    id: "kn-danladi-nasidi",
    name: "Danladi Nasidi Housing Estate (\"Gida Dubu\")",
    state: "Kano", type: "Government",
    lat: 12.0250, lng: 8.5750,
    area: "Mariri / Maiduguri Road",
    lga: "Kano Municipal",
    unitTypes: "Low-cost residential",
    status: "Completed",
    units: "Locally nicknamed \"one thousand houses\" — exact count unconfirmed",
    priceRange: null,
    agency: AGENCIES.KANO_GOVT.name,
    enquiryContact: AGENCIES.KANO_GOVT,
    sourceNote: "Fully occupied. Source: Daily Trust — verify before publishing."
  },
  {
    id: "kn-jaoji",
    name: "Ja'oji Housing Estate",
    state: "Kano", type: "Government",
    lat: 12.0022, lng: 8.5920,
    area: "Kano metropolis",
    lga: "Kano Municipal",
    unitTypes: "2–6 room courtyard houses",
    status: "Completed",
    units: "112–128 units (sources vary)",
    priceRange: null,
    agency: AGENCIES.KANO_GOVT.name,
    enquiryContact: AGENCIES.KANO_GOVT,
    sourceNote: "Historic estate, built 1964–67, handed to Kano State 1967 by the Greater Kano Planning Authority. Source: academic journal (OmniScience) — verify before publishing."
  },
  {
    id: "kn-kundila",
    name: "Kundila Housing Estate",
    state: "Kano", type: "Government",
    lat: 11.9900, lng: 8.5300,
    area: "Gyadi-Gyadi / Unguwa Uku, Zaria Road",
    lga: "Nassarawa",
    unitTypes: "2 bed flats among a mixed unit plan, built in 3 phases",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.KANO_GOVT.name,
    enquiryContact: AGENCIES.KANO_GOVT,
    sourceNote: "Historic estate, built from 1971 by joint federal & state governments. Source: academic journal (OmniScience) — verify before publishing."
  },

  // ---------------------------------------------------------------
  // ENUGU STATE — Government
  // ---------------------------------------------------------------
  {
    id: "en-coal-city-view",
    name: "Coal City View Satellite Estate",
    state: "Enugu", type: "Government",
    lat: 6.4700, lng: 7.5200,
    area: "Abor, near New Market Bridge",
    lga: "Enugu East",
    unitTypes: "1, 2 & 3 bedroom bungalows",
    status: "In Progress",
    units: "750 units (2 phases: 350 + 400)",
    priceRange: null,
    agency: AGENCIES.ESHDC.name,
    enquiryContact: AGENCIES.ESHDC,
    sourceNote: "Built for civil servants with Alpha Mead Development Co., Mahfas Group, AG Mortgage Bank. Source: The Sun, Guardian — verify before publishing."
  },
  {
    id: "en-elim-estate",
    name: "Elim Estate",
    state: "Enugu", type: "Government",
    lat: 6.4500, lng: 7.5400,
    area: "Nike",
    lga: "Enugu East",
    unitTypes: "3 bed detached (75), 2 bed semi-detached flats (89), 2 bed terrace (32), 1 bed terrace (128)",
    status: "Completed",
    units: "324 units",
    priceRange: null,
    agency: AGENCIES.FMBN.name,
    enquiryContact: AGENCIES.FMBN,
    sourceNote: "Commissioned July 2014 by Pres. Jonathan; built by COPEN Group. ESHDC separately ran a 100-unit civil-servant lottery here in 2016. Source: Daily Post — verify before publishing."
  },
  {
    id: "en-winners-estate",
    name: "Winners Estate (FMBN–I-Connect)",
    state: "Enugu", type: "Government",
    lat: 6.4650, lng: 7.5150,
    area: "Legacy Layout, behind New GRA, Trans-Ekulu",
    lga: "Enugu North",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: "254 units",
    priceRange: null,
    agency: AGENCIES.FMBN.name,
    enquiryContact: AGENCIES.FMBN,
    sourceNote: "Handed over May 2023; Cooperative Housing Development Loan with I-Connect Investment Ltd. Source: Ikenga Online — verify before publishing."
  },
  {
    id: "en-graceland",
    name: "Graceland Estate",
    state: "Enugu", type: "Government",
    lat: 6.4550, lng: 7.5450,
    area: "Coal City Eastern Extension Layout",
    lga: "Enugu East",
    unitTypes: "Unconfirmed",
    status: "In Progress",
    units: "Shares a 10,000-unit / 260 ha target with Rehoboth & Mercyville",
    priceRange: null,
    agency: "COPEN Group, under the Renewed Hope Housing Programme, with ESHDC",
    enquiryContact: AGENCIES.ESHDC,
    sourceNote: "Groundbreaking Oct 9, 2024. Source: ThisDay, thewhistler.ng — verify before publishing."
  },
  {
    id: "en-rehoboth",
    name: "Rehoboth Estate",
    state: "Enugu", type: "Government",
    lat: 6.4560, lng: 7.5460,
    area: "Coal City Eastern Extension Layout",
    lga: "Enugu East",
    unitTypes: "Unconfirmed",
    status: "In Progress",
    units: "Shares a 10,000-unit / 260 ha target with Graceland & Mercyville",
    priceRange: null,
    agency: "COPEN Group, under the Renewed Hope Housing Programme, with ESHDC",
    enquiryContact: AGENCIES.ESHDC,
    sourceNote: "Groundbreaking Oct 2024. Source: Africa Housing News — verify before publishing."
  },
  {
    id: "en-mercyville",
    name: "Mercyville Estate",
    state: "Enugu", type: "Government",
    lat: 6.4570, lng: 7.5470,
    area: "Coal City Eastern Extension Layout",
    lga: "Enugu East",
    unitTypes: "Unconfirmed",
    status: "In Progress",
    units: "Shares a 10,000-unit / 260 ha target with Graceland & Rehoboth",
    priceRange: null,
    agency: "COPEN Group, under the Renewed Hope Housing Programme, with ESHDC",
    enquiryContact: AGENCIES.ESHDC,
    sourceNote: "Groundbreaking Oct 2024. Source: Africa Housing News — verify before publishing."
  },
  {
    id: "en-unity-estate",
    name: "Unity Estate",
    state: "Enugu", type: "Government",
    lat: 6.4300, lng: 7.4800,
    area: "Umuchigbo",
    lga: "Enugu South",
    unitTypes: "Unconfirmed",
    status: "Announced",
    units: null,
    priceRange: null,
    agency: AGENCIES.ESHDC.name,
    enquiryContact: AGENCIES.ESHDC,
    sourceNote: "Announced June 2025. Source: enugustate.gov.ng — verify before publishing."
  },
  {
    id: "en-dolphin-estate",
    name: "Dolphin Estate",
    state: "Enugu", type: "Government",
    lat: 6.4580, lng: 7.5480,
    area: "Coal City Eastern Extension Alliance",
    lga: "Enugu East",
    unitTypes: "Unconfirmed",
    status: "Announced",
    units: null,
    priceRange: null,
    agency: AGENCIES.ESHDC.name,
    enquiryContact: AGENCIES.ESHDC,
    sourceNote: "Announced June 2025. Source: enugustate.gov.ng — verify before publishing."
  },
  {
    id: "en-university-estate",
    name: "University Estate",
    state: "Enugu", type: "Government",
    lat: 6.8480, lng: 7.3960,
    area: "Nsukka, by Ikenga Hotel",
    lga: "Nsukka",
    unitTypes: "Unconfirmed",
    status: "Announced",
    units: null,
    priceRange: null,
    agency: AGENCIES.ESHDC.name,
    enquiryContact: AGENCIES.ESHDC,
    sourceNote: "Announced June 2025. Source: enugustate.gov.ng — verify before publishing."
  },
  {
    id: "en-river-view",
    name: "River View Estate (Phase 2 Extension 3)",
    state: "Enugu", type: "Government",
    lat: 6.3800, lng: 7.4700,
    area: "Ozalla 4-Corner",
    lga: "Nkanu West",
    unitTypes: "Unconfirmed",
    status: "In Progress",
    units: null,
    priceRange: null,
    agency: AGENCIES.ESHDC.name,
    enquiryContact: AGENCIES.ESHDC,
    sourceNote: "Phases 1 & 2 reported inaugurated Sept 2024; Phase 2 Extension 3 announced June 2025. Source: enugustate.gov.ng, The Sun — verify before publishing."
  },
  {
    id: "en-blossom-garden",
    name: "Blossom Garden Estate",
    state: "Enugu", type: "Government",
    lat: 6.4680, lng: 7.5180,
    area: "Trans-Ekulu Annex",
    lga: "Enugu North",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.ESHDC.name,
    enquiryContact: AGENCIES.ESHDC,
    sourceNote: "Inaugurated Sept 2024. Source: The Sun — verify before publishing."
  },
  {
    id: "en-coal-city-alliance",
    name: "Coal City Eastern Extension Alliance Estate",
    state: "Enugu", type: "Government",
    lat: 6.4450, lng: 7.4900,
    area: "Independence Layout Phase 2",
    lga: "Enugu North",
    unitTypes: "Unconfirmed (marketed as a premium/elite enclave)",
    status: "Announced",
    units: null,
    priceRange: null,
    agency: AGENCIES.ESHDC.name,
    enquiryContact: AGENCIES.ESHDC,
    sourceNote: "Announced June 2025. Source: enugustate.gov.ng — verify before publishing."
  },
  {
    id: "en-gateway-owo",
    name: "Gateway Estate",
    state: "Enugu", type: "Government",
    lat: 6.3200, lng: 7.5800,
    area: "Owo",
    lga: "Nkanu East",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.ESHDC.name,
    enquiryContact: AGENCIES.ESHDC,
    sourceNote: "Inaugurated Sept 2024. Source: The Sun — verify before publishing."
  },
  {
    id: "en-smart-city-nsukka",
    name: "GRA Extension \"Smart City\" Estate",
    state: "Enugu", type: "Government",
    lat: 6.8300, lng: 7.4100,
    area: "Obimo, Nsukka",
    lga: "Nsukka",
    unitTypes: "Serviced plots (450–2,000 sqm), high/mid/low-density",
    status: "Announced",
    units: null,
    priceRange: null,
    agency: AGENCIES.ESHDC.name + " (with My Eya Homes)",
    enquiryContact: AGENCIES.ESHDC,
    sourceNote: "Plot-allocation scheme, not built units. Launched, reported March 2026. Source: Housing TV Africa — verify before publishing."
  },
  {
    id: "en-himalayas",
    name: "Himalayas Estate",
    state: "Enugu", type: "Government",
    lat: 6.6500, lng: 7.4600,
    area: "Along Enugu–Nsukka Road, past Iyikwu River",
    lga: "Igbo-Eze South",
    unitTypes: "Residential & commercial plots",
    status: "In Progress",
    units: "2,080 plots on 115.7 ha",
    priceRange: null,
    agency: AGENCIES.ESHDC.name,
    enquiryContact: AGENCIES.ESHDC,
    sourceNote: "Under litigation/community land dispute since 2020–2021. Source: Vanguard — verify before publishing."
  },
  {
    id: "en-family-homes-nsukka",
    name: "Family Homes Funds Estate, Nsukka",
    state: "Enugu", type: "Government",
    lat: 6.8500, lng: 7.3980,
    area: "Nsukka",
    lga: "Nsukka",
    unitTypes: "Unconfirmed",
    status: "In Progress",
    units: "500 units",
    priceRange: null,
    agency: AGENCIES.FHFL.name,
    enquiryContact: AGENCIES.FHFL,
    sourceNote: "Lower-confidence, single-source (2021 roundup of state initiatives). Source: legit.ng — verify before publishing."
  },
  {
    id: "en-family-homes-esut",
    name: "Family Homes Funds Estate, ESUT Gate",
    state: "Enugu", type: "Government",
    lat: 6.4200, lng: 7.5100,
    area: "By ESUT (Enugu State University of Science & Technology) gate",
    lga: "Enugu East",
    unitTypes: "Unconfirmed",
    status: "In Progress",
    units: "250 units",
    priceRange: null,
    agency: AGENCIES.FHFL.name,
    enquiryContact: AGENCIES.FHFL,
    sourceNote: "Lower-confidence, single-source (2021 roundup of state initiatives). Source: legit.ng — verify before publishing."
  },
  {
    id: "en-transparency-estate",
    name: "Transparency Estate",
    state: "Enugu", type: "Government",
    lat: 6.4350, lng: 7.4900,
    area: "Off Zik's Avenue, Uwani",
    lga: "Enugu South",
    unitTypes: "Site-and-services plots",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.ESHDC.name,
    enquiryContact: AGENCIES.ESHDC,
    sourceNote: "Developed under the Ugwuanyi administration, reported 2017. Source: The Nation, Nigeria Property Centre — verify before publishing."
  },
  {
    id: "en-heritage-estate",
    name: "Heritage Estate",
    state: "Enugu", type: "Government",
    lat: 6.4300, lng: 7.4850,
    area: "Near Zik's Residence",
    lga: "Enugu South",
    unitTypes: "Semi-detached duplexes, low-density",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.ESHDC.name,
    enquiryContact: AGENCIES.ESHDC,
    sourceNote: "Developed under the Ugwuanyi administration, reported 2017. Source: The Nation — verify before publishing."
  },
  {
    id: "en-citadel-estate",
    name: "Citadel Estate",
    state: "Enugu", type: "Government",
    lat: 6.4460, lng: 7.4960,
    area: "Independence Layout",
    lga: "Enugu North",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.ESHDC.name,
    enquiryContact: AGENCIES.ESHDC,
    sourceNote: "High-income phase 1 & 2, developed under the Ugwuanyi administration, reported 2017. Source: The Nation, Vanguard — verify before publishing."
  },
  {
    id: "en-fha-trans-ekulu",
    name: "Federal Housing Estate, Trans-Ekulu",
    state: "Enugu", type: "Government",
    lat: 6.4630, lng: 7.5100,
    area: "Trans-Ekulu",
    lga: "Enugu North",
    unitTypes: "Residential plots/houses",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.FHA.name,
    enquiryContact: AGENCIES.FHA,
    sourceNote: "Legacy scheme, undated origin. Source: Nigeria Property Centre (secondary-market listing) — verify before publishing."
  },
  {
    id: "en-renewed-hope-city",
    name: "Renewed Hope City, Enugu (planned)",
    state: "Enugu", type: "Government",
    lat: 6.4413, lng: 7.4988,
    area: "South-East zonal site, exact location not yet confirmed publicly",
    lga: "Enugu",
    unitTypes: "Unconfirmed",
    status: "Announced",
    units: "~2,000 planned",
    priceRange: null,
    agency: AGENCIES.FHA.name + " / " + AGENCIES.FMHUD.name,
    enquiryContact: AGENCIES.FMHUD,
    sourceNote: "Pin marks Enugu city centre as a symbolic location — exact site not yet public. Source: The Cable, Housing TV Africa — verify before publishing."
  },
  {
    id: "en-kateland",
    name: "Kateland Estate",
    state: "Enugu", type: "Government",
    lat: 6.4670, lng: 7.5170,
    area: "Phase 6/7, Trans Ekulu",
    lga: "Enugu North",
    unitTypes: "Residential land plots",
    status: "In Progress",
    units: null,
    priceRange: "₦18,000,000/plot",
    agency: "Hymac Real Ltd, in partnership with " + AGENCIES.ESHDC.name,
    enquiryContact: AGENCIES.ESHDC,
    sourceNote: "Private developer (Hymac/Hyfield) building on ESHDC-partnered land — a public-private scheme, not purely private. Source: eshdc.en.gov.ng, Nigeria Property Centre — verify before publishing."
  },
  {
    id: "en-conquest-estate",
    name: "Conquest (Garden) Estate",
    state: "Enugu", type: "Government",
    lat: 6.4680, lng: 7.5190,
    area: "Trans Ekulu Phase 6 extension",
    lga: "Enugu North",
    unitTypes: "Residential land plots (50/100 sqm), buy-and-build",
    status: "In Progress",
    units: null,
    priceRange: "₦10,000,000/plot",
    agency: "Toshel Nigeria Ltd, in partnership with " + AGENCIES.ESHDC.name,
    enquiryContact: AGENCIES.ESHDC,
    sourceNote: "Private developer building on ESHDC-partnered/allocated land. Source: naijalandlord.com — verify before publishing."
  },

  // ---------------------------------------------------------------
  // PRIVATE ESTATES — Ogun, Kano, Enugu (seed set)
  // ---------------------------------------------------------------
  {
    id: "pv-queens-park",
    name: "Queens Park Estate (Phase 1 & 2)",
    state: "Ogun", type: "Private",
    lat: 6.8150, lng: 3.4450,
    area: "Mowe-Ofada, near Sagamu Interchange",
    lga: "Obafemi Owode",
    unitTypes: "600sqm plots (for 2–3 bed bungalows)",
    status: "In Progress",
    units: null,
    priceRange: "₦6,000,000/plot",
    agency: "LCR Limited (Landmark Corporate Realty)",
    enquiryContact: { name: "LCR Limited", phone: null, email: null, website: "https://qpemowe.lcrng.com/" },
    sourceNote: "Land-plot estate (buy-land-then-build). Source: LCR/Landmark, Nigeria Property Centre — verify before publishing."
  },
  {
    id: "pv-oak-ville-green",
    name: "Oak Ville Green Estate",
    state: "Ogun", type: "Private",
    lat: 6.8100, lng: 3.4400,
    area: "Orile-Imo, Mowe-Ofada",
    lga: "Obafemi Owode",
    unitTypes: "300/500sqm plots, 1 acre",
    status: "In Progress",
    units: null,
    priceRange: "₦4.5M – ₦42M (per reseller listing, may not reflect current pricing)",
    agency: "Developer linked to Queens Park Estate (LCR)",
    enquiryContact: { name: "TPI Homes (reseller)", phone: null, email: null, website: "https://www.tpihomes.com.ng/property/introducing-oak-ville-green-estate-mowe-ofada/" },
    sourceNote: "One reseller listing marks it sold out — other agents may still have inventory. Source: TPI Homes, Sureland — verify before publishing."
  },
  {
    id: "pv-emerald-garden-city",
    name: "Emerald Garden City (Phase 1 & 1B)",
    state: "Ogun", type: "Private",
    lat: 6.8130, lng: 3.4480,
    area: "Mowe-Ofada, near Lagos-Ibadan Expressway",
    lga: "Obafemi Owode",
    unitTypes: "300/400/600sqm plots",
    status: "In Progress",
    units: null,
    priceRange: "₦2.0M – ₦5.7M",
    agency: "Merit Abode Nigeria Limited",
    enquiryContact: { name: "Merit Abode Nigeria Limited", phone: null, email: null, website: "https://meritabode.com/emerald-garden-city-mowe-ofada/" },
    sourceNote: "Land-plot estate, active development. Source: meritabode.com — verify before publishing."
  },
  {
    id: "pv-imperial-park",
    name: "Imperial Park and Gardens (\"Sugarland Estate\")",
    state: "Ogun", type: "Private",
    lat: 6.8500, lng: 3.6350,
    area: "Regal College Road, GRA Extension, Sagamu",
    lga: "Sagamu",
    unitTypes: "Land plots, planned apartments/duplexes/bungalows",
    status: "In Progress",
    units: null,
    priceRange: "From ₦6,000,000 (600sqm plot)",
    agency: "Adron Homes and Properties",
    enquiryContact: { name: "Adron Homes and Properties", phone: null, email: null, website: "https://adronhomesproperties.com/property/imperial-park-and-gardens-exclusive-adron-homes/" },
    sourceNote: "Source: Adron Homes, Nigeria Property Centre — verify before publishing."
  },
  {
    id: "pv-southgate-park",
    name: "Southgate Park & Gardens",
    state: "Ogun", type: "Private",
    lat: 7.1700, lng: 3.3900,
    area: "Alabata / Alamala, Abeokuta",
    lga: "Abeokuta North",
    unitTypes: "540sqm plots",
    status: "In Progress",
    units: null,
    priceRange: "₦3M – ₦5M",
    agency: "Adron Homes and Properties",
    enquiryContact: { name: "Adron Homes and Properties", phone: null, email: null, website: "https://adronhomesproperties.com/property/sunrise-park-gardens/" },
    sourceNote: "Also marketed as \"Sunrise Park & Gardens\". Source: Adron Homes, PrivateProperty — verify before publishing."
  },
  {
    id: "pv-wealth-city-redeem",
    name: "Wealth City Redeem",
    state: "Ogun", type: "Private",
    lat: 6.7250, lng: 3.4800,
    area: "Along Lagos/Ibadan Expressway, near RCCG Camp",
    lga: "Obafemi Owode",
    unitTypes: "Land plots (residential/investment)",
    status: "In Progress",
    units: null,
    priceRange: "Price on request",
    agency: "Arash Homes International",
    enquiryContact: { name: "Arash Homes International", phone: null, email: null, website: "https://arashhomesinternational.com/property/wealth-city-redeem-ogun-state/" },
    sourceNote: "Source: Arash Homes International — verify before publishing."
  },
  {
    id: "pv-flourish-city-kano",
    name: "Flourish City Estate",
    state: "Kano", type: "Private",
    lat: 11.9500, lng: 8.4700,
    area: "Off Zaria Road, Kwanar Dawaki",
    lga: "Gwale",
    unitTypes: "350–450sqm plots",
    status: "In Progress",
    units: null,
    priceRange: "₦1.75M – ₦3.5M",
    agency: "PWAN (Property World Africa Network)",
    enquiryContact: { name: "PWAN Homes", phone: null, email: null, website: "https://www.pwanhomes.com/estates/northern/kano" },
    sourceNote: "Certificate of Occupancy reported in progress. Source: PWAN Homes, El-Dorado Homes — verify before publishing."
  },
  {
    id: "pv-newtown-wudil",
    name: "Newtown Estate, Wudil",
    state: "Kano", type: "Private",
    lat: 11.8100, lng: 8.8400,
    area: "Wudil, near Aliko Dangote University of Science & Technology",
    lga: "Wudil",
    unitTypes: "250/350/500sqm plots + commercial plots",
    status: "In Progress",
    units: null,
    priceRange: "₦1.75M – ₦2.8M",
    agency: "Real Estate Generals (developer name unconfirmed)",
    enquiryContact: { name: "Real Estate Generals", phone: null, email: null, website: null },
    sourceNote: "Weakest-sourced entry in this set — no single canonical source page found, verify directly before treating as confirmed."
  },
  {
    id: "pv-flourish-city-enugu",
    name: "Flourish City Estate",
    state: "Enugu", type: "Private",
    lat: 6.4950, lng: 7.3900,
    area: "Ameke Ngwo, 9th Mile, Udi LGA",
    lga: "Udi",
    unitTypes: "500sqm plots",
    status: "In Progress",
    units: null,
    priceRange: "₦4,500,000/plot",
    agency: "Vikkystar Real Estate / PWAN",
    enquiryContact: { name: "PWAN", phone: null, email: null, website: "https://pwan.com.ng/flourish-city-estate-agbogazi-nike-enugu-the-smart-investors-golden-ticket/" },
    sourceNote: "The cleanest purely-private example found in Enugu. Source: PWAN — verify before publishing."
  }
];
