// Nigeria Government & Private Housing Estates — structured data
// Compiled from public news/government sources. See data.md for the
// original Lagos working notes. FCT and Rivers entries were compiled the
// same way: public agency sites, news coverage, and real estate
// aggregators, not verified government records.
//
// Coordinates are neighbourhood-level approximations (geocoded from place
// names), not verified street addresses. Good enough to place a pin on a
// map for a demo; not good enough to route a courier.
//
// type: "Government" — initiated, land-granted, or financed by a
//   government body (federal, state, or a public-private partnership
//   where the public partner is the anchor). "Private" — a commercial
//   developer's own project, no government initiation.

const AGENCIES = {
  HOMS: {
    name: "Lagos State Mortgage Board (Lagos HOMS)",
    phone: "07044519311 / 08124817363",
    email: "info@lagoshoms.gov.ng",
    website: "https://www.lagoshoms.gov.ng"
  },
  LSDPC: {
    name: "Lagos State Development and Property Corporation (LSDPC)",
    phone: null,
    email: null,
    website: "https://lsdpc.gov.ng"
  },
  LAGOS_MINISTRY: {
    name: "Lagos State Ministry of Housing",
    phone: null,
    email: null,
    website: "https://housing.lagosstate.gov.ng"
  },
  FMHUD: {
    name: "Federal Ministry of Housing & Urban Development (FMHUD)",
    phone: null,
    email: null,
    website: "https://fmhud.gov.ng"
  },
  FHA: {
    name: "Federal Housing Authority (FHA)",
    phone: "+234 911 541 8960",
    email: "info@fha.gov.ng",
    website: "https://fha.gov.ng"
  },
  FCDA: {
    name: "Federal Capital Development Authority (FCDA)",
    phone: "+234 9 234 1525",
    email: null,
    website: "https://fcda.gov.ng"
  },
  RSHPDA: {
    name: "Rivers State Housing and Property Development Authority (RSHPDA)",
    phone: "+234 703 554 7870",
    email: "info@rshpda.gov.ng",
    website: "https://rshpda.gov.ng"
  },
  FMBN: {
    name: "Federal Mortgage Bank of Nigeria (FMBN)",
    phone: null,
    email: null,
    website: "https://www.fmbn.gov.ng"
  },
  RIVERS_GOVT: {
    name: "Rivers State Government",
    phone: null,
    email: null,
    website: "https://riversstate.gov.ng"
  }
};

// Federal mortgage financing option shown as a general, non-endorsing
// link-out — not tied to any specific estate's developer network.
const MREIF = {
  name: "MREIF (Mortgage Refinance Initiative Fund)",
  rate: "9.75% p.a. fixed",
  term: "Up to 20 years",
  equity: "From 10% equity",
  signupUrl: "https://housing.mreif.com.ng/sign-up",
  prequalifyUrl: "https://housing.mreif.com.ng/pre-qualifier",
  infoUrl: "https://www.mreif.com.ng/",
  disclaimer: "Federal mortgage program managed by ARM for Ministry of Finance Incorporated. housedata.ng is not affiliated with MREIF and cannot confirm any specific estate is in MREIF's approved developer network — check eligibility directly."
};

const ESTATES = [
  // ---------------------------------------------------------------
  // LAGOS — Government
  // ---------------------------------------------------------------
  {
    id: "lagos-oba-adeboruwa",
    name: "Oba Adeboruwa Estate",
    state: "Lagos", type: "Government",
    lat: 6.6100, lng: 3.5150,
    area: "Igbogbo, Ikorodu",
    lga: "Ikorodu",
    unitTypes: "1, 2, 3 bed flats",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.HOMS.name,
    enquiryContact: AGENCIES.HOMS,
    sourceNote: "Completed, rent-to-own available. Source: NPC, EleniyanCares — publicly reported, verify before publishing."
  },
  {
    id: "lagos-millennium-i",
    name: "Millennium Housing Scheme",
    state: "Lagos", type: "Government",
    lat: 6.6180, lng: 3.2980,
    area: "Iloro, Agege",
    lga: "Agege",
    unitTypes: "3 bed flats",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.LAGOS_MINISTRY.name,
    enquiryContact: AGENCIES.LAGOS_MINISTRY,
    sourceNote: "Source: NPC — publicly reported, verify before publishing."
  },
  {
    id: "lagos-millennium-ii",
    name: "Millennium Housing Scheme II",
    state: "Lagos", type: "Government",
    lat: 6.6480, lng: 3.2870,
    area: "Ojokoro, Ijaiye",
    lga: "Ijaiye",
    unitTypes: "3 bed flats",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.LAGOS_MINISTRY.name,
    enquiryContact: AGENCIES.LAGOS_MINISTRY,
    sourceNote: "Source: NPC — publicly reported, verify before publishing."
  },
  {
    id: "lagos-jubilee",
    name: "Jubilee Housing Estate",
    state: "Lagos", type: "Government",
    lat: 6.5900, lng: 3.9700,
    area: "Odoragunshin, Epe",
    lga: "Epe",
    unitTypes: "Room & parlour, 1 & 2 bed bungalows",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.LAGOS_MINISTRY.name,
    enquiryContact: AGENCIES.LAGOS_MINISTRY,
    sourceNote: "Source: NPC — publicly reported, verify before publishing."
  },
  {
    id: "lagos-jakande-garden",
    name: "Jakande Garden Estate",
    state: "Lagos", type: "Government",
    lat: 6.5200, lng: 3.2270,
    area: "Igando",
    lga: "Alimosho",
    unitTypes: "Flats",
    status: "Completed",
    units: "492 units",
    priceRange: null,
    agency: AGENCIES.LSDPC.name,
    enquiryContact: AGENCIES.LSDPC,
    sourceNote: "Source: Ballers.ng — publicly reported, verify before publishing."
  },
  {
    id: "lagos-iponri",
    name: "Iponri Estate",
    state: "Lagos", type: "Government",
    lat: 6.4931, lng: 3.3627,
    area: "Iponri",
    lga: "Surulere",
    unitTypes: "Various",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.LSDPC.name,
    enquiryContact: AGENCIES.LSDPC,
    sourceNote: "Surulere / Lagos Island axis. Source: Ballers.ng — publicly reported, verify before publishing."
  },
  {
    id: "lagos-homs-ibeshe",
    name: "Lagos HOMS – Ibeshe",
    state: "Lagos", type: "Government",
    lat: 6.6330, lng: 3.5460,
    area: "Ibeshe, Ikorodu",
    lga: "Ikorodu",
    unitTypes: "Residential",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.HOMS.name,
    enquiryContact: AGENCIES.HOMS,
    sourceNote: "Source: Estate Intel — publicly reported, verify before publishing."
  },
  {
    id: "lagos-homs-ajah",
    name: "Lagos HOMS Apartment – Ajah",
    state: "Lagos", type: "Government",
    lat: 6.4675, lng: 3.5711,
    area: "Mobile Estate Rd, Ajah",
    lga: "Eti-Osa",
    unitTypes: "1, 2, 3 bed",
    status: "Completed",
    units: "84 units",
    priceRange: null,
    agency: AGENCIES.HOMS.name,
    enquiryContact: AGENCIES.HOMS,
    sourceNote: "Completed July 2020. Source: Estate Intel — publicly reported, verify before publishing."
  },
  {
    id: "lagos-igbogbo-iib",
    name: "Igbogbo IIB",
    state: "Lagos", type: "Government",
    lat: 6.6080, lng: 3.5190,
    area: "Igbogbo",
    lga: "Ikorodu",
    unitTypes: "1, 2, 3 bed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.HOMS.name,
    enquiryContact: AGENCIES.HOMS,
    sourceNote: "Source: EleniyanCares — publicly reported, verify before publishing."
  },
  {
    id: "lagos-sangotedo",
    name: "Sangotedo Scheme",
    state: "Lagos", type: "Government",
    lat: 6.4590, lng: 3.6270,
    area: "Sangotedo",
    lga: "Eti-Osa",
    unitTypes: "1, 2, 3 bed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.HOMS.name,
    enquiryContact: AGENCIES.HOMS,
    sourceNote: "Eti-Osa / Ajah axis. Source: EleniyanCares — publicly reported, verify before publishing."
  },
  {
    id: "lagos-ajara",
    name: "Ajara Estate",
    state: "Lagos", type: "Government",
    lat: 6.4130, lng: 2.8500,
    area: "Badagry",
    lga: "Badagry",
    unitTypes: "1 bed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.LAGOS_MINISTRY.name,
    enquiryContact: AGENCIES.LAGOS_MINISTRY,
    sourceNote: "Source: EleniyanCares — publicly reported, verify before publishing."
  },
  {
    id: "lagos-bayview",
    name: "Bayview Estate",
    state: "Lagos", type: "Government",
    lat: 6.4415, lng: 3.5090,
    area: "Ikate-Elegushi, Lekki",
    lga: "Eti-Osa",
    unitTypes: "Residential",
    status: "Completed",
    units: "100 units",
    priceRange: null,
    agency: AGENCIES.LAGOS_MINISTRY.name,
    enquiryContact: AGENCIES.LAGOS_MINISTRY,
    sourceNote: "Opened by Gov. Sanwo-Olu. Source: Wikipedia — publicly reported, verify before publishing."
  },
  {
    id: "lagos-gbagada",
    name: "Gbagada Housing Estate",
    state: "Lagos", type: "Government",
    lat: 6.5535, lng: 3.3880,
    area: "Gbagada",
    lga: "Kosofe",
    unitTypes: "Mixed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.LSDPC.name,
    enquiryContact: AGENCIES.LSDPC,
    sourceNote: "Existing/established. Source: Propsult — publicly reported, verify before publishing."
  },
  {
    id: "lagos-ikorodu-scheme",
    name: "Ikorodu Housing Scheme",
    state: "Lagos", type: "Government",
    lat: 6.6018, lng: 3.5106,
    area: "Ikorodu",
    lga: "Ikorodu",
    unitTypes: "Mixed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.LAGOS_MINISTRY.name,
    enquiryContact: AGENCIES.LAGOS_MINISTRY,
    sourceNote: "Existing/established. Source: Propsult — publicly reported, verify before publishing."
  },
  {
    id: "lagos-alausa",
    name: "Alausa Housing Estate",
    state: "Lagos", type: "Government",
    lat: 6.6059, lng: 3.3491,
    area: "Alausa",
    lga: "Ikeja",
    unitTypes: "Mixed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.LSDPC.name,
    enquiryContact: AGENCIES.LSDPC,
    sourceNote: "Existing/established. Source: Propsult — publicly reported, verify before publishing."
  },
  {
    id: "lagos-lekki-agbowa",
    name: "Lekki Apartments (Agbowa)",
    state: "Lagos", type: "Government",
    lat: 6.6660, lng: 3.7280,
    area: "Agbowa-Sagamu Rd",
    lga: "Ikosi-Ejirin LCDA",
    unitTypes: "48x2 bed, 24x3 bed",
    status: "Completed",
    units: "72 units (8.22 hectares)",
    priceRange: null,
    agency: AGENCIES.LSDPC.name,
    enquiryContact: AGENCIES.LSDPC,
    sourceNote: "Source: Propsult — publicly reported, verify before publishing."
  },
  {
    id: "lagos-satellite-town",
    name: "Satellite Town Estate",
    state: "Lagos", type: "Government",
    lat: 6.4633, lng: 3.2843,
    area: "Lagos-Badagry Expwy",
    lga: "Amuwo-Odofin",
    unitTypes: "Mixed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.LSDPC.name,
    enquiryContact: AGENCIES.LSDPC,
    sourceNote: "Long-established, older government estate. Source: NigerianQueries — publicly reported, verify before publishing."
  },
  {
    id: "lagos-new-homes-1250",
    name: "1,250 New Homes (multi-site)",
    state: "Lagos", type: "Government",
    lat: 6.6280, lng: 3.3460,
    area: "Multi-site: Igbogbo, Sangotedo, Iponri, Gbagada, Omole",
    lga: "Multiple LGAs",
    unitTypes: "Mixed, across 5 sites",
    status: "Announced",
    units: "1,250 units",
    priceRange: null,
    agency: AGENCIES.LAGOS_MINISTRY.name,
    enquiryContact: AGENCIES.LAGOS_MINISTRY,
    sourceNote: "Announced May 2024, 6-month target. Pin marks approximate centre of a multi-site project — not a single address. Source: Ballers.ng — verify before publishing."
  },
  {
    id: "lagos-affordable-50bn",
    name: "₦50bn Affordable Housing Scheme",
    state: "Lagos", type: "Government",
    lat: 6.6059, lng: 3.3491,
    area: "State-wide",
    lga: "State-wide",
    unitTypes: "Mixed",
    status: "Announced",
    units: "10,000 homes (target 2026)",
    priceRange: null,
    agency: AGENCIES.LAGOS_MINISTRY.name,
    enquiryContact: AGENCIES.LAGOS_MINISTRY,
    sourceNote: "Announced May 2025. Pin marks the Ministry of Housing HQ at Alausa as a symbolic location, not a project site. Source: Ballers.ng — verify before publishing."
  },
  {
    id: "lagos-renewed-hope-housing",
    name: "Renewed Hope Housing (Federal collab)",
    state: "Lagos", type: "Government",
    lat: 6.6270, lng: 3.2790,
    area: "Ipaja and Ibeju-Lekki",
    lga: "Alimosho / Ibeju-Lekki",
    unitTypes: "Mixed",
    status: "In Progress",
    units: "2,000+ units",
    priceRange: null,
    agency: AGENCIES.FMHUD.name,
    enquiryContact: AGENCIES.FMHUD,
    sourceNote: "Federal-state collaboration; additional estates planned in Badagry and Epe. Pin marks the Ipaja site. Source: Ballers.ng — verify before publishing."
  },
  {
    id: "lagos-renewed-hope-city",
    name: "Renewed Hope City Project",
    state: "Lagos", type: "Government",
    lat: 6.4459, lng: 3.9370,
    area: "Ibeju-Lekki",
    lga: "Ibeju-Lekki",
    unitTypes: "Housing units",
    status: "In Progress",
    units: "2,000 units",
    priceRange: null,
    agency: AGENCIES.FMHUD.name,
    enquiryContact: AGENCIES.FMHUD,
    sourceNote: "Construction ongoing; land provided by Lagos State. Source: FMHUD — verify before publishing."
  },

  // ---------------------------------------------------------------
  // FCT (ABUJA) — Government
  // ---------------------------------------------------------------
  {
    id: "fct-gwarinpa",
    name: "Gwarinpa Estate",
    state: "FCT", type: "Government",
    lat: 9.1000, lng: 7.4100,
    area: "Gwarinpa",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "Mixed flats/duplexes",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.FHA.name,
    enquiryContact: AGENCIES.FHA,
    sourceNote: "One of Africa's largest housing estates by plot count; developed from the 1990s in phases. Unit total unconfirmed. Source: SabiAbuja — verify before publishing."
  },
  {
    id: "fct-lugbe",
    name: "FHA Lugbe Estate",
    state: "FCT", type: "Government",
    lat: 8.9930, lng: 7.3660,
    area: "Lugbe District",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "Flats, terraces",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.FHA.name,
    enquiryContact: AGENCIES.FHA,
    sourceNote: "Source: FHA Information Memorandum, Nigeria Property Centre — verify before publishing."
  },
  {
    id: "fct-zuba",
    name: "FHA Zuba Estate",
    state: "FCT", type: "Government",
    lat: 9.1440, lng: 7.1980,
    area: "Zuba, near Zuba Model Market",
    lga: "Bwari Area Council",
    unitTypes: "1, 2 & 3 bed flats, 3 bed terrace duplex",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.FHA.name,
    enquiryContact: AGENCIES.FHA,
    sourceNote: "Units reported sold out. FHA's site separately lists a \"Zuba Mass Housing Project\" as ongoing — unclear if same or a follow-on phase. Source: FHA — verify before publishing."
  },
  {
    id: "fct-kwali",
    name: "Kwali Mass Housing Project",
    state: "FCT", type: "Government",
    lat: 8.8770, lng: 7.0140,
    area: "Kwali",
    lga: "Kwali Area Council",
    unitTypes: "Unconfirmed",
    status: "In Progress",
    units: null,
    priceRange: null,
    agency: AGENCIES.FHA.name,
    enquiryContact: AGENCIES.FHA,
    sourceNote: "Listed as ongoing on FHA's own projects page; no unit count or completion date published. Source: fha.gov.ng — verify before publishing."
  },
  {
    id: "fct-apo-hill",
    name: "Apo Hill Estate",
    state: "FCT", type: "Government",
    lat: 8.9850, lng: 7.4870,
    area: "Apo Hill",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "Unconfirmed",
    status: "In Progress",
    units: "900+ units",
    priceRange: null,
    agency: AGENCIES.FHA.name,
    enquiryContact: AGENCIES.FHA,
    sourceNote: "PPP project; groundbreaking Dec 2009, still listed as ongoing. Source: fha.gov.ng — verify before publishing."
  },
  {
    id: "fct-paradise-hills",
    name: "Paradise Hills Estate (FHA/ENL, Apo-Guzape)",
    state: "FCT", type: "Government",
    lat: 9.0080, lng: 7.5300,
    area: "Apo/Guzape, Asokoro Extension",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "2–5 bed apartments, terraces and detached/semi-detached duplexes",
    status: "In Progress",
    units: "822 planned (574 phase-1 complete, ~69%)",
    priceRange: null,
    agency: AGENCIES.FHA.name,
    enquiryContact: AGENCIES.FHA,
    sourceNote: "FHA/ENL Consortium PPP. FHA's own site cites a conflicting 932-unit figure elsewhere for \"Apo Estate\" — treat unit counts as approximate. Source: paradisehillsestate.com, fha.gov.ng — verify before publishing."
  },
  {
    id: "fct-green-city",
    name: "FHA Green City Estate",
    state: "FCT", type: "Government",
    lat: 8.9600, lng: 7.4600,
    area: "Wasa District, Apo–Wasa Expressway",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "2 bed apartments, 3 bed apartments & terrace duplex, 4 bed terrace duplex",
    status: "In Progress",
    units: "216 units (one report cites 223)",
    priceRange: null,
    agency: AGENCIES.FHA.name,
    enquiryContact: AGENCIES.FHA,
    sourceNote: "PPP with Greenpasture Dynamic Land & Homes; land allocated by FCDA. Groundbreaking 24–25 Jun 2026 — construction just started. Source: Blueprint, Pointblank News — verify before publishing."
  },
  {
    id: "fct-renewed-hope-karsana",
    name: "Renewed Hope City, Karsana",
    state: "FCT", type: "Government",
    lat: 9.1250, lng: 7.4300,
    area: "Karsana (Phase IV, near Gwarinpa/Katampe/Jahi)",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "1 bed apartments, 2 bed terraces, 3 bed flats/homes",
    status: "In Progress",
    units: "3,112 planned (~1,000 near-complete as of Nov 2024)",
    priceRange: null,
    agency: AGENCIES.FMHUD.name,
    enquiryContact: AGENCIES.FMHUD,
    sourceNote: "Part of the 100,000-unit national Renewed Hope Cities and Estates programme; FCT target is 20,000 units. Source: Housing TV Africa, renewedhopehomes.fmhud.gov.ng — verify before publishing."
  },
  {
    id: "fct-nhp-dukpai",
    name: "National Housing Programme, Dukpai",
    state: "FCT", type: "Government",
    lat: 8.9430, lng: 7.0790,
    area: "Dukpai, Gwagwalada",
    lga: "Gwagwalada Area Council",
    unitTypes: "1, 2 & 3 bed flats (3 condominium blocks)",
    status: "In Progress",
    units: "72 flats",
    priceRange: null,
    agency: AGENCIES.FMHUD.name,
    enquiryContact: AGENCIES.FMHUD,
    sourceNote: "Buhari-era National Housing Programme site; one 2020 report notes a work suspension order was issued, unclear if since resolved. Source: BusinessToday NG, Pulse Nigeria — verify before publishing."
  },
  {
    id: "fct-ahooas-idu",
    name: "AHOOAS Housing Estate, Idu (Nigerian Army)",
    state: "FCT", type: "Government",
    lat: 9.0850, lng: 7.3550,
    area: "Idu",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "Flats (100 blocks of 4)",
    status: "Completed",
    units: "400 units",
    priceRange: null,
    agency: AGENCIES.FMHUD.name,
    enquiryContact: AGENCIES.FMHUD,
    sourceNote: "Built for injured soldiers and personnel; commissioned 18 Dec 2024. Federal (Nigerian Army), not FHA/FCDA. Source: Leadership NG — verify before publishing."
  },
  {
    id: "fct-bungalow-city",
    name: "Bungalow City",
    state: "FCT", type: "Government",
    lat: 9.1200, lng: 7.2500,
    area: "Dei-Dei–Zuba Expressway",
    lga: "Bwari Area Council",
    unitTypes: "2 bed detached, 3 bed terrace",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.FMBN.name,
    enquiryContact: AGENCIES.FMBN,
    sourceNote: "NHF Rent-to-Own scheme; FMBN financed, built by Brains and Hammers. Handed over 23–24 Jun 2026. Source: News Chronicle, Housing TV Africa — verify before publishing."
  },
  {
    id: "fct-prince-princess",
    name: "Prince & Princess Mass Housing Estate",
    state: "FCT", type: "Government",
    lat: 9.0500, lng: 7.4700,
    area: "Duboyi District",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.FCDA.name,
    enquiryContact: AGENCIES.FCDA,
    sourceNote: "Delivered under FCDA's Mass Housing PPP framework; FCDA notes it needs infrastructure upgrades. Source: fcda.gov.ng — verify before publishing."
  },
  {
    id: "fct-jubilation-court",
    name: "Jubilation Court Estate",
    state: "FCT", type: "Government",
    lat: 8.9950, lng: 7.4500,
    area: "Dakwo District",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.FCDA.name,
    enquiryContact: AGENCIES.FCDA,
    sourceNote: "FCDA Mass Housing PPP, developer Crystal-Link Aluminum Products Ltd. Source: fcda.gov.ng — verify before publishing."
  },
  {
    id: "fct-jubilation-bethel",
    name: "Jubilation Bethel Estate",
    state: "FCT", type: "Government",
    lat: 8.9900, lng: 7.4550,
    area: "Lokogoma District",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.FCDA.name,
    enquiryContact: AGENCIES.FCDA,
    sourceNote: "FCDA Mass Housing PPP, developer Nemmacol Nigeria Ltd. Source: fcda.gov.ng — verify before publishing."
  },
  {
    id: "fct-frsc-lokogoma",
    name: "FRSC Staff Housing Estate",
    state: "FCT", type: "Government",
    lat: 8.9900, lng: 7.4550,
    area: "Lokogoma District",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.FCDA.name,
    enquiryContact: AGENCIES.FCDA,
    sourceNote: "FCDA Mass Housing PPP, FRSC Staff Housing Co-operative Society. Source: fcda.gov.ng — verify before publishing."
  },
  {
    id: "fct-katampe-ppp",
    name: "Katampe District PPP Housing Scheme",
    state: "FCT", type: "Government",
    lat: 9.1100, lng: 7.4450,
    area: "Katampe District",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "Unconfirmed",
    status: "In Progress",
    units: null,
    priceRange: null,
    agency: AGENCIES.FCDA.name,
    enquiryContact: AGENCIES.FCDA,
    sourceNote: "Reported ~23.5% complete, work suspended; developer Deanshanger Projects Ltd, ₦61.19bn project cost. Source: fcda.gov.ng — verify before publishing."
  },
  {
    id: "fct-mabushi-ppp",
    name: "Mabushi District PPP Housing Scheme",
    state: "FCT", type: "Government",
    lat: 9.0850, lng: 7.4350,
    area: "Mabushi District",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "Unconfirmed",
    status: "Announced",
    units: null,
    priceRange: null,
    agency: AGENCIES.FCDA.name,
    enquiryContact: AGENCIES.FCDA,
    sourceNote: "Preferred bidder selected; build-out progress unconfirmed. Source: fcda.gov.ng — verify before publishing."
  },
  {
    id: "fct-kado",
    name: "FHA Kado Estate",
    state: "FCT", type: "Government",
    lat: 9.0800, lng: 7.4200,
    area: "Kado, near Jabi Lake",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "Mixed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.FHA.name,
    enquiryContact: AGENCIES.FHA,
    sourceNote: "Source: SabiAbuja — verify before publishing."
  },
  {
    id: "fct-kubwa",
    name: "FHA Kubwa Housing Scheme",
    state: "FCT", type: "Government",
    lat: 9.1580, lng: 7.3320,
    area: "Kubwa (Phase 2, Phase 3)",
    lga: "Bwari Area Council",
    unitTypes: "Mixed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.FHA.name,
    enquiryContact: AGENCIES.FHA,
    sourceNote: "Source: SabiAbuja — verify before publishing."
  },

  // ---------------------------------------------------------------
  // RIVERS STATE — Government
  // ---------------------------------------------------------------
  {
    id: "rv-greater-taf-city",
    name: "Greater TAF City",
    state: "Rivers", type: "Government",
    lat: 4.8600, lng: 7.0100,
    area: "Obirikwere, Airport Road",
    lga: "Obio/Akpor",
    unitTypes: "2 bed bungalows to 4 bed duplexes",
    status: "In Progress",
    units: "20,000 planned (Phase 1: 1,000 units, commissioned Dec 2025)",
    priceRange: null,
    agency: "Rivers State Government + TAF Africa Global (Greater PH City Development Authority + Pricewise Homes)",
    enquiryContact: AGENCIES.RIVERS_GOVT,
    sourceNote: "Rivers State-led PPP, rhetorically tied to but distinct from FHA's federal Renewed Hope programme. Source: The Nation, Hallmark News — verify before publishing."
  },
  {
    id: "rv-ph-airportcity",
    name: "Port Harcourt AirportCity",
    state: "Rivers", type: "Government",
    lat: 4.9930, lng: 6.9490,
    area: "Omagwa, near PH International Airport",
    lga: "Ikwerre",
    unitTypes: "1–5 bed \"smart homes\"",
    status: "Announced",
    units: "2,000 planned (initial phase)",
    priceRange: null,
    agency: "Rivers State Government (via GPCDA, 30%) + Masta Services Ltd (70%)",
    enquiryContact: AGENCIES.RIVERS_GOVT,
    sourceNote: "Partnership signed 2025; 80-hectare site. Source: Guardian Nigeria, PropertyAccess.ng — verify before publishing."
  },
  {
    id: "rv-iriebe",
    name: "Iriebe Housing Estate",
    state: "Rivers", type: "Government",
    lat: 4.8700, lng: 7.0700,
    area: "Off Aba Expressway",
    lga: "Obio/Akpor",
    unitTypes: "2 & 3 bed bungalows, 1 & 2 bed flats",
    status: "In Progress",
    units: "834 planned (300+ occupied as of 2014 — figure likely stale)",
    priceRange: null,
    agency: AGENCIES.RSHPDA.name,
    enquiryContact: AGENCIES.RSHPDA,
    sourceNote: "Financed with FMBN/NHF support; most recent public occupancy figure found dates to 2014. Source: The Tide — verify before publishing, occupancy likely higher now."
  },
  {
    id: "rv-fha-trans-amadi",
    name: "FHA Estate, Old Trans-Amadi/Rumueme",
    state: "Rivers", type: "Government",
    lat: 4.7900, lng: 7.0350,
    area: "Trans-Amadi / Rumueme",
    lga: "Port Harcourt City",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: "207 units",
    priceRange: null,
    agency: AGENCIES.FHA.name,
    enquiryContact: AGENCIES.FHA,
    sourceNote: "Allocated on mortgage terms 1987/1990. Source: fha.gov.ng/past-projects — verify before publishing."
  },
  {
    id: "rv-elekahia",
    name: "Elekahia Housing Estate",
    state: "Rivers", type: "Government",
    lat: 4.8000, lng: 7.0450,
    area: "Elekahia",
    lga: "Obio/Akpor",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.RSHPDA.name,
    enquiryContact: AGENCIES.RSHPDA,
    sourceNote: "Existing/legacy estate; RSHPDA lists it by name only, no unit count published. Source: rshpda.gov.ng — verify before publishing."
  },
  {
    id: "rv-rumuibekwe",
    name: "Rumuibekwe Housing Estate",
    state: "Rivers", type: "Government",
    lat: 4.8500, lng: 7.0200,
    area: "Rumuibekwe",
    lga: "Obio/Akpor",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.RSHPDA.name,
    enquiryContact: AGENCIES.RSHPDA,
    sourceNote: "Existing/legacy estate; RSHPDA lists it by name only, no unit count published. Source: rshpda.gov.ng — verify before publishing."
  },
  {
    id: "rv-rumuobiakani",
    name: "Rumuobiakani Housing Estate",
    state: "Rivers", type: "Government",
    lat: 4.8450, lng: 7.0150,
    area: "Rumuobiakani",
    lga: "Obio/Akpor",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.RSHPDA.name,
    enquiryContact: AGENCIES.RSHPDA,
    sourceNote: "Existing/legacy estate; RSHPDA lists it by name only, no unit count published. Source: rshpda.gov.ng — verify before publishing."
  },
  {
    id: "rv-abuloma",
    name: "Abuloma Housing Estate (Phases I–III)",
    state: "Rivers", type: "Government",
    lat: 4.7600, lng: 7.0450,
    area: "Abuloma waterfront",
    lga: "Port Harcourt City",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.RSHPDA.name,
    enquiryContact: AGENCIES.RSHPDA,
    sourceNote: "Existing/legacy estate; RSHPDA lists it by name only, no unit count published. Source: rshpda.gov.ng — verify before publishing."
  },
  {
    id: "rv-presidential",
    name: "Presidential Housing Estate",
    state: "Rivers", type: "Government",
    lat: 4.8156, lng: 7.0300,
    area: "Port Harcourt (exact sub-area unconfirmed)",
    lga: "Port Harcourt City",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.RSHPDA.name,
    enquiryContact: AGENCIES.RSHPDA,
    sourceNote: "Existing/legacy estate; RSHPDA lists it by name only, no unit count published, location approximate. Source: rshpda.gov.ng — verify before publishing."
  },
  {
    id: "rv-ndoki",
    name: "Ndoki Waterfront Estate",
    state: "Rivers", type: "Government",
    lat: 4.7700, lng: 7.0500,
    area: "Port Harcourt waterfront (exact sub-area unconfirmed)",
    lga: "Port Harcourt City",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.RSHPDA.name,
    enquiryContact: AGENCIES.RSHPDA,
    sourceNote: "Existing/legacy estate; RSHPDA lists it by name only, no unit count published, location approximate. Source: rshpda.gov.ng — verify before publishing."
  },
  {
    id: "rv-aggrey",
    name: "Aggrey Waterfront Estate",
    state: "Rivers", type: "Government",
    lat: 4.7850, lng: 7.0250,
    area: "Aggrey Road axis",
    lga: "Port Harcourt City",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.RSHPDA.name,
    enquiryContact: AGENCIES.RSHPDA,
    sourceNote: "Existing/legacy estate; RSHPDA lists it by name only, no unit count published. Source: rshpda.gov.ng — verify before publishing."
  },
  {
    id: "rv-marine-base",
    name: "Marine Base Waterfront Estate",
    state: "Rivers", type: "Government",
    lat: 4.7750, lng: 7.0150,
    area: "Marine Base",
    lga: "Port Harcourt City",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.RSHPDA.name,
    enquiryContact: AGENCIES.RSHPDA,
    sourceNote: "Existing/legacy estate; RSHPDA lists it by name only, no unit count published. Source: rshpda.gov.ng — verify before publishing."
  },
  {
    id: "rv-diobu",
    name: "Diobu Housing Estate (Mile I, II, III)",
    state: "Rivers", type: "Government",
    lat: 4.8100, lng: 6.9950,
    area: "Diobu",
    lga: "Port Harcourt City",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.RSHPDA.name,
    enquiryContact: AGENCIES.RSHPDA,
    sourceNote: "Existing/legacy estate. Source: National Network — verify before publishing."
  },
  {
    id: "rv-ph-township",
    name: "Port Harcourt Township Housing Estate",
    state: "Rivers", type: "Government",
    lat: 4.7800, lng: 7.0100,
    area: "Old Township area",
    lga: "Port Harcourt City",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.RSHPDA.name,
    enquiryContact: AGENCIES.RSHPDA,
    sourceNote: "Existing/legacy estate. Source: National Network — verify before publishing."
  },
  {
    id: "rv-rumuomasi",
    name: "Rumuomasi Housing Estate",
    state: "Rivers", type: "Government",
    lat: 4.8250, lng: 7.0300,
    area: "Rumuomasi",
    lga: "Obio/Akpor",
    unitTypes: "Unconfirmed",
    status: "Completed",
    units: null,
    priceRange: null,
    agency: AGENCIES.RSHPDA.name,
    enquiryContact: AGENCIES.RSHPDA,
    sourceNote: "Existing/legacy estate. Source: National Network — verify before publishing."
  },
  {
    id: "rv-rainbow-town",
    name: "Rainbow Town",
    state: "Rivers", type: "Government",
    lat: 4.7950, lng: 7.0400,
    area: "Trans Amadi",
    lga: "Port Harcourt City",
    unitTypes: "Apartments, terraces, duplexes, penthouses",
    status: "In Progress",
    units: "~1,181 planned",
    priceRange: null,
    agency: "Rivers State Government + First Bank Nigeria (JV: CityScape International Development Plc)",
    enquiryContact: AGENCIES.RIVERS_GOVT,
    sourceNote: "Public-private JV, not a purely private development. Detached houses/terraces completed 2015; tower phases reportedly stalled since. Source: Estate Intel, BusinessDay archive — verify before publishing."
  },

  // ---------------------------------------------------------------
  // PRIVATE ESTATES — seed set (developer self-submission planned;
  // these were sourced from public listings/aggregators in the meantime)
  // ---------------------------------------------------------------
  {
    id: "pv-lekki-gardens",
    name: "Lekki Gardens Estate",
    state: "Lagos", type: "Private",
    lat: 6.4650, lng: 3.5900,
    area: "Ajah / Lekki Peninsula II",
    lga: "Eti-Osa",
    unitTypes: "2–4 bed terrace duplexes, flats",
    status: "In Progress",
    units: null,
    priceRange: "₦27M – ₦650M (avg ~₦120M)",
    agency: "Lekki Gardens Homes & Properties Ltd (private developer)",
    enquiryContact: { name: "Lekki Gardens Homes & Properties Ltd", phone: null, email: null, website: "https://lekkigardens.com/" },
    sourceNote: "Phased development, some phases complete, others still selling. Source: PropertyPro.ng, lekkigardens.com — verify before publishing."
  },
  {
    id: "pv-pinnock-beach",
    name: "Pinnock Beach Estate",
    state: "Lagos", type: "Private",
    lat: 6.4460, lng: 3.5280,
    area: "Osapa, Lekki",
    lga: "Eti-Osa",
    unitTypes: "Duplexes, land plots",
    status: "Completed",
    units: null,
    priceRange: "₦125M – ₦4B (avg ~₦1.5B)",
    agency: "UPDC (UAC of Nigeria Plc subsidiary)",
    enquiryContact: { name: "UPDC Plc", phone: null, email: null, website: "https://nigeriapropertycentre.com/for-sale/houses/lagos/lekki/osapa/showtype?n=pinnock+beach+estate" },
    sourceNote: "Source: NigeriaPropertyCentre — verify before publishing."
  },
  {
    id: "pv-megamound",
    name: "Megamound Estate",
    state: "Lagos", type: "Private",
    lat: 6.4500, lng: 3.5500,
    area: "Lekki",
    lga: "Eti-Osa",
    unitTypes: "Duplexes, flats",
    status: "In Progress",
    units: null,
    priceRange: "₦50M – ₦1.5B (avg ~₦420M)",
    agency: "Megamound Real Estate & Construction Group",
    enquiryContact: { name: "Megamound Real Estate & Construction Group", phone: null, email: null, website: "https://megamound.com/" },
    sourceNote: "Source: megamound.com, NigeriaPropertyCentre — verify before publishing."
  },
  {
    id: "pv-northern-foreshore",
    name: "Northern Foreshore Estate",
    state: "Lagos", type: "Private",
    lat: 6.4430, lng: 3.5350,
    area: "Osapa / Chevron, Lekki",
    lga: "Eti-Osa",
    unitTypes: "Duplexes, land",
    status: "In Progress",
    units: null,
    priceRange: "Price on request",
    agency: "Aircom Nigeria",
    enquiryContact: { name: "Aircom Nigeria", phone: null, email: null, website: "http://www.aircomng.com/northern-foreshore/" },
    sourceNote: "Source: aircomng.com, Estate Intel — verify before publishing."
  },
  {
    id: "pv-alaro-city",
    name: "Alaro City (Universal Homes phase)",
    state: "Lagos", type: "Private",
    lat: 6.4550, lng: 3.7100,
    area: "Lekki Free Zone, Epe",
    lga: "Ibeju-Lekki",
    unitTypes: "2 bed apartments and up",
    status: "In Progress",
    units: "Phase 1: ~576 units, due end 2026",
    priceRange: "From $79,950",
    agency: "Rendeavour / Universal Homes",
    enquiryContact: { name: "Alaro City / Rendeavour", phone: null, email: null, website: "https://www.alarocity.com/now-selling/homes/" },
    sourceNote: "Source: alarocity.com, BusinessDay — verify before publishing."
  },
  {
    id: "pv-brains-hammers",
    name: "Brains and Hammers Estate",
    state: "FCT", type: "Private",
    lat: 9.1000, lng: 7.4300,
    area: "Life Camp / Katampe / Jabi corridor",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "Duplexes, terraces, flats",
    status: "In Progress",
    units: null,
    priceRange: "₦60M – ₦380M (avg ~₦80M)",
    agency: "Brains and Hammers Ltd",
    enquiryContact: { name: "Brains and Hammers Ltd", phone: null, email: null, website: "https://brainsandhammers.com/" },
    sourceNote: "Source: brainsandhammers.com, NigeriaPropertyCentre — verify before publishing."
  },
  {
    id: "pv-trademore",
    name: "Trademore Estate",
    state: "FCT", type: "Private",
    lat: 8.9850, lng: 7.3600,
    area: "Lugbe District",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "Terrace, semi-detached, detached duplexes",
    status: "Completed",
    units: null,
    priceRange: "₦6M – ₦16M+ (listing appears dated)",
    agency: "Trademore International Holdings Ltd",
    enquiryContact: { name: "Trademore International Holdings Ltd", phone: null, email: null, website: "https://trademoreestates.com/" },
    sourceNote: "Estate was affected by a notable flood event in 2022. Price figures read as several years old — treat as indicative only. Source: trademoreestates.com, NigeriaPropertyCentre — verify before publishing."
  },
  {
    id: "pv-efab-city",
    name: "Efab City Estate",
    state: "FCT", type: "Private",
    lat: 9.0900, lng: 7.4150,
    area: "Mbora District",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "Flats, duplexes, bungalows, condos",
    status: "In Progress",
    units: null,
    priceRange: "₦75M – ₦130M+",
    agency: "Efab Properties",
    enquiryContact: { name: "Efab Properties", phone: null, email: null, website: "https://efabproperties.com/efabproperties/estates/efab-city-estate-mbora-district/index.html" },
    sourceNote: "Source: efabproperties.com — verify before publishing."
  },
  {
    id: "pv-cosgrove-guzape",
    name: "Cosgrove Smart Estate",
    state: "FCT", type: "Private",
    lat: 9.0100, lng: 7.5250,
    area: "Guzape",
    lga: "Abuja Municipal (AMAC)",
    unitTypes: "7 bed smart villas",
    status: "In Progress",
    units: "5 units",
    priceRange: "Price on request",
    agency: "Cosgrove Investment Ltd (Cosgrove Africa)",
    enquiryContact: { name: "Cosgrove Africa", phone: null, email: null, website: "https://cosgroveafrica.com/projects/cosgrove_smart_estate_guzape" },
    sourceNote: "Boutique/luxury scale — 5 units, smaller than a typical estate. Source: cosgroveafrica.com — verify before publishing."
  },
  {
    id: "pv-garden-heights",
    name: "Garden Heights Estate",
    state: "Rivers", type: "Private",
    lat: 4.8250, lng: 7.0250,
    area: "GRA Phase III",
    lga: "Port Harcourt City",
    unitTypes: "Studio, 1–3 bed apartments, semi-detached bungalows, detached duplexes",
    status: "In Progress",
    units: "Scheme 1: ~24 units; ~600 planned across 4 schemes",
    priceRange: "Price on request",
    agency: "Port Harcourt Gardens Limited (PGL)",
    enquiryContact: { name: "Port Harcourt Gardens Limited", phone: null, email: null, website: "https://guardian.ng/property/developer-unveils-port-harcourts-garden-heights-estate/" },
    sourceNote: "Source: The Guardian Nigeria — verify before publishing."
  },
  {
    id: "pv-suncity-gardens",
    name: "Suncity Gardens Estate",
    state: "Rivers", type: "Private",
    lat: 4.8350, lng: 7.0450,
    area: "Peter Odili Road",
    lga: "Obio/Akpor",
    unitTypes: "Studio, 2–3 bed apartments, 4 bed terrace, 5 bed duplex",
    status: "In Progress",
    units: null,
    priceRange: "From ₦7M (listing appears dated, ~2021)",
    agency: "Suncity Gardens Estate Ltd",
    enquiryContact: { name: "Suncity Gardens Estate Ltd", phone: null, email: null, website: "https://suncitygarden.org/" },
    sourceNote: "Pricing likely stale. Source: suncitygarden.org — verify before publishing."
  }
];
